import {test,expect} from '@playwright/test';
const water={id:'w1',district:'KEPEZ',neighborhood:'GÖKSU MAHALLESİ',startsAt:'2026-10-08T10:25:00+03:00',endsAt:null,source:'SuKesintileri.com.tr',sourceUrl:'https://www.sukesintileri.com.tr/antalya-su-kesintisi-sorgulama'};
const electric={id:'e1',startsAt:'2026-10-09T00:28:06+03:00',endsAt:'2026-10-09T02:28:06+03:00',message:'Ekip çalışıyor',locations:[{district:'FİNİKE',neighborhood:'HASYURT'}],geometry:{type:'MultiPolygon',coordinates:[[[[30.7,36.9],[30.71,36.9],[30.71,36.91],[30.7,36.9]]]]},source:'AEDAŞ',sourceUrl:'https://kesinti.akdenizedas.com.tr/'};
test.beforeEach(async({page})=>{await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));await page.route('https://tiles.openfreemap.org/styles/positron',r=>r.fulfill({json:{version:8,sources:{},layers:[{id:'bg',type:'background',paint:{'background-color':'#f7f5f1'}}]}}));});
test('traffic stays embedded, refreshes and returns to stops',async({page})=>{
 // Keep pointer coverage on the pinned browser engines. With an external
 // Chromium override, activate the button by keyboard to avoid its emulated
 // cross-origin pointer race; native permission/GPS assertions remain intact.
 await page.route('**/api/transit?**',r=>r.fulfill({json:{stops:[],coverage:[],partial:false}}));let requests=0;
 await page.route('https://yandex.com.tr/map-widget/**',r=>{requests++;return r.fulfill({contentType:'text/html',body:`<button onclick="navigator.geolocation.getCurrentPosition(p=>document.getElementById('result').textContent=p.coords.latitude+','+p.coords.longitude,e=>document.getElementById('result').textContent=e.message)">Konum</button><p id="result"></p>`});});
 await page.goto('/?preview');await page.getByRole('button',{name:'Ulaşım',exact:true}).click();await page.getByRole('button',{name:'Trafik',exact:true}).click();
 const frame=page.locator('iframe[title="Canlı trafik haritası"]');await expect(frame).toBeVisible();await expect(page.getByLabel('Trafikte yer ara')).toBeVisible();await expect(frame).toHaveAttribute('allow',/geolocation/);const locationButton=page.frameLocator('iframe').getByRole('button',{name:'Konum',exact:true});if(process.env.CHROMIUM_EXECUTABLE)await locationButton.press('Enter');else await locationButton.click();await expect(page.frameLocator('iframe').locator('#result')).toHaveText('36.884,30.704');await page.getByLabel('Trafikte yer ara').fill('Tonguç Caddesi');await expect.poll(async()=>new URL((await frame.getAttribute('src'))!).searchParams.get('text')).toBe('Tonguç Caddesi');await expect(frame).toHaveAttribute('src',/l=map%2Ctrf/);const before=requests;await page.getByRole('button',{name:'Trafik haritasını yenile'}).click();await expect.poll(()=>requests).toBeGreaterThan(before);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Duraklar',exact:true}).click();await expect(frame).toHaveCount(0);await expect(page.getByRole('heading',{name:'Yakın duraklar'})).toBeVisible();
});
test('compact outages, district search, electric area and failures',async({page})=>{
 let fail=false,count=0;await page.route('**/api/outages?**',r=>{count++;return r.fulfill(fail?{status:503,json:{error:'unavailable'}}:{json:{items:r.request().url().includes('electric')?[electric]:[water,{...water,id:'w2',district:'MURATPAŞA',neighborhood:'GÜZELOBA'}],fetchedAt:new Date().toISOString(),partial:false}});});
 await page.goto('/?preview');await page.getByRole('button',{name:'Kesintiler',exact:true}).click();await expect(page.locator('.outage-card')).toHaveCount(2);await expect(page.getByLabel('İlçe seç')).toHaveCount(0);await expect(page.locator('.outage-notice')).toHaveCount(0);await page.getByLabel('Kesinti ara').fill('KEPEZ');await expect(page.locator('.outage-card')).toHaveCount(1);
 await page.getByLabel('Kesinti ara').fill('bulunamaz');await expect(page.locator('.outage-card')).toHaveCount(0);await page.getByLabel('Kesinti ara').fill('');await page.getByRole('button',{name:'Elektrik',exact:true}).click();await expect(page.getByText('HASYURT',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Etkilenen alanı göster'}).click();await expect(page.locator('.outage-map canvas')).toBeVisible();await expect(page.locator('.outage-card')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 fail=true;await page.getByRole('button',{name:'Kesintileri yenile'}).click();await expect(page.getByRole('alert')).toContainText('Kesintiler alınamadı.');await expect(page.locator('.outage-card')).toHaveCount(0);fail=false;await page.getByRole('button',{name:'Tekrar dene',exact:true}).click();await expect(page.locator('.outage-card')).toHaveCount(1);expect(count).toBeGreaterThan(2);
});
test('events use search without category filters and preserve coordinates',async({page})=>{
 const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());await page.route('**/api/events',r=>r.fulfill({json:{items:[{id:'a',title:'Çocuk oyunu',startsAt:day+'T00:00:00+03:00',endsAt:day+'T23:59:59+03:00',venue:'Türkan Şoray Kültür Merkezi',source:'Muratpaşa Belediyesi',priceLabel:'Ücretsiz',kind:'children',url:'https://kultursanat.muratpasa-bld.gov.tr/etkinlik-takvimi',directionsUrl:'https://www.google.com/maps/dir/?api=1&destination=36.869878259538474,30.72455969241696'},{id:'b',title:'Resim sergisi',startsAt:day+'T00:00:00+03:00',endsAt:day+'T23:59:59+03:00',kind:'exhibition',venue:'Galeri',source:'Muratpaşa Belediyesi',url:'https://kultursanat.muratpasa-bld.gov.tr/etkinlik-takvimi'}],partial:false}}));await page.goto('/?preview');await page.getByRole('button',{name:'Etkinlik',exact:true}).click();await expect(page.locator('.event-card')).toHaveCount(2);await page.getByLabel('Etkinlik ara').fill('çocuk');await expect(page.locator('.event-card')).toHaveCount(1);await expect(page.locator('.event-card')).toContainText('Ücretsiz');await expect(page.getByRole('link',{name:'Yol tarifi',exact:true})).toHaveAttribute('href',/destination=36\.869/);await expect(page.getByRole('button',{name:'Sergi',exact:true})).toHaveCount(0);await page.getByLabel('Etkinlik ara').fill('sergi');await expect(page.locator('.event-card')).toContainText('Resim sergisi');await expect(page.getByRole('link',{name:'Yol tarifi',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('all opens first and fuel beyond the small initial viewport is retained',async({page})=>{
 const station={id:'fuel:1',name:'Opet',category:'fuel',lat:36.92,lng:30.71,address:'İstasyon adresi'};
 await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[station]}}));await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[{type:'way',id:3,center:{lat:36.93,lon:30.72},tags:{amenity:'fuel'}}]}}));
 await page.addInitScript(()=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.884,lng:30.704,savedAt:Date.now(),mode:'manual'})));
 await page.goto('/');await expect(page.locator('.category-rail button').first()).toHaveText('Tümü');await expect(page.locator('.category-rail button').first()).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Akaryakıt',exact:true}).click();await expect(page.locator('.place-row')).toHaveCount(2);await expect(page.locator('.places-list')).toContainText('Opet');await expect(page.locator('.places-list')).toContainText('Akaryakıt istasyonu');
});
