import {test,expect,type Page} from '@playwright/test';
const hour=Math.floor(Date.now()/3600000)*3600;
async function base(page:Page,location={lat:36.88,lng:30.7}){
 await page.addInitScript(c=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({...c,mode:'manual',savedAt:Date.now()})),location);
 await page.route('**/api/location?**',r=>r.fulfill({json:{label:location.lat>40?'İstanbul':'Antalya'}}));
 await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));
 await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));
 await page.route('**/api/fishing?**',r=>r.fulfill({json:{hourly:[{time:hour,airTemperature:22,feelsLike:23,rain:0,wind:2,visibility:10000}],daily:[{time:hour,uv:4}],fetchedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+900000).toISOString()}}));
 await page.route('https://tiles.openfreemap.org/styles/positron',r=>r.fulfill({json:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#f7f5f1'}}]}}));
}
async function category(page:Page,name:string){await page.getByRole('button',{name:'Tüm kategorileri aç',exact:true}).click();await page.getByRole('dialog',{name:'Tüm kategoriler',exact:true}).getByRole('button',{name,exact:true}).click();}
test('new categories show unnamed public infrastructure, facts and map details within 5 km',async({page})=>{
 await base(page);await page.route('**/api/nearby?**',r=>{const url=new URL(r.request().url());return r.fulfill({json:url.searchParams.get('kind')==='discovery'?{elements:[{type:'node',id:1,lat:36.91,lon:30.7,tags:{amenity:'toilets',fee:'no',changing_table:'yes'}},{type:'node',id:2,lat:36.88,lon:30.7,tags:{amenity:'toilets',access:'private'}},{type:'node',id:3,lat:36.881,lon:30.7,tags:{amenity:'charging_station',name:'Deneme Şarj','socket:type2':'2','socket:type2:output':'22 kW'}}]}:{places:[]}});});
 await page.goto('/');await page.getByRole('button',{name:'Tüm kategorileri aç',exact:true}).click();const picker=page.getByRole('dialog',{name:'Tüm kategoriler'});for(const name of ['Tuvalet','İçme suyu','Şarj','Oyun alanı','Spor','Veteriner','Geri dönüşüm','Kamp','Piknik','Manzara','Müze','Plaj'])await expect(picker.getByRole('button',{name,exact:true})).toHaveCount(1);await picker.getByRole('button',{name:'Tuvalet',exact:true}).click();await expect(page.locator('.place-row')).toHaveCount(1);await expect(page.locator('.place-row')).toContainText('Ücretsiz');await expect(page.locator('.place-row')).toContainText('Bebek bakım alanı');await page.locator('.place-row').click();await page.getByRole('dialog',{name:'Tuvalet',exact:true}).getByText('Kaynak ve lisans',{exact:true}).click();await expect(page.getByRole('link',{name:'OpenStreetMap · Lisans'})).toHaveAttribute('href','https://www.openstreetmap.org/copyright');await page.getByRole('button',{name:'Kapat',exact:true}).click();await category(page,'Şarj');await expect(page.locator('.place-row')).toContainText('Type 2');await page.locator('.place-row').click();await expect(page.getByRole('dialog',{name:'Deneme Şarj',exact:true})).toContainText('22 kW');await page.getByRole('button',{name:'Kapat',exact:true}).click();await page.getByRole('button',{name:'Harita',exact:true}).click();await expect(page.locator('.map-stage')).toHaveAttribute('data-place-count','1');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('Istanbul municipal parking survives other source failures and clears outside its coverage',async({page})=>{
 await base(page,{lat:41.01,lng:28.97});await page.route('**/api/viewport?**',r=>r.fulfill({status:503,json:{error:'offline'}}));await page.route('**/api/overture?**',r=>r.fulfill({status:503,json:{error:'offline'}}));const urls:string[]=[];await page.route('**/api/nearby?**',r=>{urls.push(r.request().url());const u=new URL(r.request().url());return r.fulfill({json:u.searchParams.get('layer')==='municipal'?{places:[{id:'ibb:park:1',name:'Deneme İSPARK',category:'parking',lat:41.012,lng:28.97,address:'Fatih',source:'İBB / İSPARK',licenseUrl:'https://data.ibb.gov.tr/license',availability:{free:0,total:100,open:true,fetchedAt:new Date().toISOString()}}]}:{pm2_5:12,pm10:20,european_aqi:30,time:hour}});});
 await page.goto('/');await category(page,'Otopark');await expect(page.locator('.place-row')).toContainText('0 boş / 100');await expect(page.getByText('Yerler alınamadı',{exact:true})).toHaveCount(0);await page.locator('.place-row').click();const detail=page.getByRole('dialog',{name:'Deneme İSPARK',exact:true});await expect(detail).toContainText('Alındı');await detail.getByText('Kaynak ve lisans',{exact:true}).click();await expect(detail.getByRole('link',{name:'İBB / İSPARK · Lisans'})).toHaveAttribute('href','https://data.ibb.gov.tr/license');await expect(detail).toContainText('CC BY 4.0');await page.getByRole('button',{name:'Kapat',exact:true}).click();const before=urls.filter(u=>u.includes('layer=municipal')).length;await page.addInitScript(()=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.88,lng:30.7,mode:'manual',savedAt:Date.now()})));await page.reload();await category(page,'Otopark');await expect(page.locator('.place-row')).toHaveCount(0);expect(urls.filter(u=>u.includes('layer=municipal')).length).toBe(before);
});
test('air summary labels model data, preserves zero and shows missing values',async({page})=>{
 await base(page);await page.route('**/api/nearby?**',r=>r.fulfill({json:{pm2_5:0,pm10:null,european_aqi:30,time:hour,fetchedAt:new Date().toISOString()}}));await page.goto('/');const air=page.locator('.air-quality');await expect(air.locator('summary')).toContainText('Makul (model)');await air.locator('summary').click();await expect(air.locator('.detail-metrics strong').nth(0)).toHaveText('0');await expect(air.locator('.detail-metrics strong').nth(1)).toHaveText('Veri yok');await expect(air).toContainText('CAMS / Open-Meteo');await expect(air.getByRole('link',{name:'CC BY 4.0'})).toHaveAttribute('href','https://creativecommons.org/licenses/by/4.0/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('air provider failure is retryable and does not manufacture clean air',async({page})=>{
 await base(page);let failed=true;await page.route('**/api/nearby?**',r=>failed?r.fulfill({status:503,json:{error:'air_unavailable'}}):r.fulfill({json:{pm2_5:22,pm10:40,european_aqi:70,time:hour,fetchedAt:new Date().toISOString()}}));await page.goto('/');const air=page.locator('.air-quality');await air.locator('summary').click();await expect(air).toContainText('Veri alınamadı.');await expect(air.locator('.detail-metrics')).toHaveCount(0);failed=false;await air.getByRole('button',{name:'Yenile',exact:true}).click();await expect(air.locator('summary')).toContainText('Kötü (model)');
});
test('category-specific supplementary search finds places hidden by the general result limit',async({page})=>{
 await base(page);await page.route('**/api/nearby?**',r=>r.fulfill({status:503,json:{error:'unavailable'}}));const urls:string[]=[];await page.route('**/api/overture?**',r=>{urls.push(r.request().url());const selected=new URL(r.request().url()).searchParams.get('category')==='charging';return r.fulfill({json:{places:selected?[{id:'overture:ev',name:'Deneme EV',category:'charging',lat:36.90,lng:30.70,address:'Antalya',source:'Overture Maps',licenseUrl:'https://docs.overturemaps.org/attribution/'}]:Array.from({length:300},(_,i)=>({id:'overture:cafe'+i,name:'Kafe '+i,category:'cafe',lat:36.88,lng:30.7,address:'Antalya'}))}});});await page.goto('/');await category(page,'Şarj');await expect(page.locator('.place-row')).toHaveCount(1);await expect(page.locator('.place-row')).toContainText('Deneme EV');expect(urls.some(u=>u.includes('category=charging'))).toBe(true);await page.getByRole('button',{name:'Harita',exact:true}).click();await expect(page.locator('.map-stage')).toHaveAttribute('data-place-count','1');
});
