import {test,expect} from '@playwright/test';
test('fishing works without GPS and changes the coastal forecast',async({page})=>{
 const now=Math.floor(Date.now()/1000);const requests:string[]=[];
 await page.route('**/api/fishing?**',r=>{requests.push(r.request().url());return r.fulfill({json:{hourly:[{time:now,wind:0,gust:4,rain:10,wave:null,period:null,temperature:24,windDirection:90,waveDirection:null,pressure:1010}],daily:[{time:now,sunrise:now-3600,sunset:now+3600,moonPhase:.5}],partial:true,fetchedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+900000).toISOString()}});});
 await page.goto('/');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(page.getByRole('heading',{name:'Kıyı balıkçılığı'})).toBeVisible();await expect(page.locator('.forecast-metrics')).toContainText('Rüzgâr0 m/sn');await expect(page.locator('.forecast-metrics')).toContainText('DalgaVeri yok');await page.getByRole('button',{name:/Konyaaltı.*Kıyı seç/}).click();await page.getByRole('button',{name:'Alanya',exact:true}).click();await expect.poll(()=>requests.some(u=>u.includes('lng=32'))).toBe(true);await expect(page.locator('.shore-select')).toContainText('Alanya');await page.getByText('Kıyıda hazırlık · Yemli / Spin',{exact:true}).click();await page.getByRole('button',{name:'Spin',exact:true}).click();await expect(page.getByText(/Atış alanını/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('price categories compare identical products separately from alternatives',async({page})=>{
 const urls:string[]=[];const offer=(market:string,price:number)=>({id:market,name:market,market,lat:36.88,lng:30.70,distanceM:100,price,unitPrice:'TL/L',updatedAt:new Date().toISOString(),promotion:null});
 await page.addInitScript(()=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.884,lng:30.704,savedAt:Date.now()})));
 await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));
 await page.route('**/api/prices?**',r=>{urls.push(r.request().url());return r.fulfill({json:{products:[{id:'same',title:'Pınar Süt',quantity:'1 L',offers:[offer('migros',50),offer('bim',60)]}],alternatives:[{id:'other',title:'Başka Süt',quantity:'500 ML',offers:[offer('sok',30)]}],depotCount:3,total:2,hasMore:false,radius:3}});});
 await page.goto('/');await page.locator('.category-rail').getByRole('button',{name:'Market',exact:true}).click();await page.getByRole('button',{name:'Ürün fiyatları',exact:true}).click();await page.getByRole('button',{name:'Süt ve süt ürünleri',exact:true}).click();await expect.poll(()=>urls.some(u=>u.includes('category=dairy'))).toBe(true);await expect(page.getByRole('heading',{name:'Aynı ürün, farklı marketler'})).toBeVisible();await expect(page.locator('.price-difference')).toContainText('%20');await expect(page.getByRole('heading',{name:'Alternatif ürünler'})).toBeVisible();await expect(page.locator('.product-price-card')).toHaveCount(2);await page.getByRole('button',{name:'Et ve balık',exact:true}).click();await expect.poll(()=>urls.some(u=>u.includes('category=meat-fish'))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('prices follow the selected city nationwide and clear previous city offers',async({page})=>{
 const cities=[{lat:41.0082,lng:28.9784,name:'İstanbul'},{lat:38.5012,lng:43.3729,name:'Van'},{lat:39.92,lng:32.85,name:'Ankara'}];const urls:string[]=[];
 await page.addInitScript(city=>{if(!localStorage.getItem('yakinim:v2:last-location'))localStorage.setItem('yakinim:v2:last-location',JSON.stringify({...city,mode:'manual',savedAt:Date.now()}));},cities[0]);
 await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));
 await page.route('**/api/prices?**',r=>{urls.push(r.request().url());const params=new URL(r.request().url()).searchParams,city=cities.find(c=>String(c.lat)===params.get('lat')&&String(c.lng)===params.get('lng'));if(!city)throw Error('Unexpected coordinates');const empty=city.name==='Ankara';return r.fulfill({json:{products:empty?[]:[{id:'same-product',title:'Pınar Süt 1 L',quantity:'1 L',offers:['migros','bim'].map((market,i)=>({id:city.name+market,name:city.name+' şubesi',market,lat:city.lat,lng:city.lng,distanceM:100,price:50+i*10,unitPrice:'TL/L',updatedAt:new Date().toISOString(),promotion:null}))}],alternatives:[],depotCount:empty?0:2,total:0,hasMore:false,radius:3}});});
 for(const city of cities){
  await page.goto('/');await page.evaluate(c=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({...c,mode:'manual',savedAt:Date.now()})),city);await page.reload();await page.locator('.category-rail').getByRole('button',{name:'Market',exact:true}).click();await page.getByRole('button',{name:'Ürün fiyatları',exact:true}).click();await page.getByRole('button',{name:'Süt ve süt ürünleri',exact:true}).click();await expect.poll(()=>urls.some(u=>new URL(u).searchParams.get('lat')===String(city.lat)&&new URL(u).searchParams.get('category')==='dairy')).toBe(true);
  if(city.name==='Ankara'){await expect(page.getByText('Bu konum çevresinde kaynakta kayıtlı şube bulunamadı.',{exact:true})).toBeVisible();await expect(page.locator('.product-price-card')).toHaveCount(0);}else{await expect(page.locator('.product-price-card')).toHaveCount(1);await expect(page.locator('.product-price-card')).toContainText(city.name+' şubesi');if(city.name==='Van')await expect(page.locator('.product-price-card')).not.toContainText('İstanbul şubesi');}
 }
});

const richForecast=()=>{const base=Math.floor(Date.now()/3600000)*3600;return {hourly:Array.from({length:40},(_,i)=>({time:base+i*3600,wind:i===0?0:3+i/10,gust:5+i/10,rain:10,wave:.3+i/100,period:4,temperature:25,windDirection:90,waveDirection:180,pressure:1010,airTemperature:22,feelsLike:23,visibility:10000,cloud:20,precipitation:0,windWave:.1,windWavePeriod:2,swell:.2,swellPeriod:6,current:.07,currentDirection:45,seaLevel:-.3})),daily:[{time:base,sunrise:base-10800,sunset:base+21600,moonPhase:.5,uv:5.4},{time:base+86400,sunrise:base+75600,sunset:base+108000,moonPhase:.6,uv:5}],partial:false,sourceAvailability:{weather:true,marine:true},coastal:true,modelDistanceM:21000,modelLocations:{marine:{lat:41.208,lng:39.708}},fetchedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+900000).toISOString()};};
async function sources(page:import('@playwright/test').Page){await page.route('**/api/fishing?**',r=>r.fulfill({json:richForecast()}));await page.route('**/api/location?**',r=>r.fulfill({json:{label:'Konyaaltı, Antalya'}}));await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));}
test('category transitions reveal the selection and sheets can reopen without trapping focus',async({page})=>{
 await sources(page);await page.goto('/?preview');const trigger=page.getByRole('button',{name:'Tüm kategorileri aç',exact:true});await trigger.click();const sheet=page.getByRole('dialog',{name:'Tüm kategoriler',exact:true});await sheet.getByRole('button',{name:'Otopark',exact:true}).click();await expect(sheet).not.toBeVisible();
 await expect.poll(()=>page.locator('.category-rail').evaluate(node=>{const active=node.querySelector('[aria-pressed=true]');if(!active)return false;const a=active.getBoundingClientRect(),r=node.getBoundingClientRect();return a.left>=r.left-1&&a.right<=r.right+1;})).toBe(true);
 await trigger.click();await page.keyboard.press('Escape');await trigger.click();await expect(sheet).toBeVisible();await expect(sheet.getByRole('button',{name:'Tüm kategoriler kapat'})).toBeFocused();await page.keyboard.press('Escape');await expect(sheet).not.toBeVisible();await expect(trigger).toBeFocused();expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');
});
test('reduced motion keeps category sheets usable without transitions',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await sources(page);await page.goto('/?preview');await page.getByRole('button',{name:'Tüm kategorileri aç',exact:true}).click();const sheet=page.getByRole('dialog',{name:'Tüm kategoriler',exact:true});await expect(sheet).toBeVisible();expect(await sheet.evaluate(node=>getComputedStyle(node).transitionDuration)).toBe('0s');await sheet.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(sheet).not.toBeVisible();await expect(page.locator('.forecast-metrics')).toBeVisible();expect(await page.locator('main').evaluate(node=>node.getAnimations().length)).toBe(0);await page.getByRole('button',{name:/Konyaaltı.*Kıyı seç/}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Kıyı seç',exact:true})).not.toBeVisible();
});
test('coastal day comparison, expanded metrics, favorite and private journal persist',async({page})=>{
 await sources(page);await page.goto('/');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(page.locator('.forecast-metrics')).toContainText(/Rüzgâr\s*0 m\/sn/);await page.getByRole('button',{name:/Konyaaltı.*Kıyı seç/}).click();const picker=page.getByRole('dialog',{name:'Kıyı seç',exact:true});await picker.getByRole('button',{name:'Karadeniz',exact:true}).click();await picker.getByRole('button',{name:'Trabzon',exact:true}).click();await expect(picker).not.toBeVisible();await expect(page.locator('.shore-select')).toContainText('Trabzon');await page.getByRole('button',{name:'Kıyıyı favorilere ekle'}).click();await expect(page.getByLabel('Favori kıyılar')).toContainText('Trabzon');await page.getByRole('button',{name:'Yarın',exact:true}).click();await expect(page.getByRole('button',{name:'Yarın',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByLabel('Tahmin saati').fill('2');await expect(page.locator('.selected-hour')).toHaveCount(1);await page.getByRole('button',{name:'Bugün',exact:true}).click();await page.getByText('Deniz, akıntı ve hava ayrıntıları',{exact:true}).click();await expect(page.locator('.detail-metrics')).toContainText('Yüzey akıntısı0,07 m/sn');await expect(page.locator('.detail-metrics')).toContainText('Günlük en yüksek UV5,4');await page.getByText(/Av günlüğüm · 0 kayıt/).click();await page.getByRole('button',{name:'Av kaydı ekle',exact:true}).click();const journal=page.getByRole('dialog',{name:'Av kaydı',exact:true});await journal.getByLabel('Tür (isteğe bağlı)').fill('Levrek');await journal.getByLabel('Adet',{exact:true}).fill('2');await journal.getByLabel('Not',{exact:true}).fill('Spin denemesi');await journal.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await expect(journal).not.toBeVisible();await expect(page.locator('.journal-entry')).toContainText('Levrek · 2 adet');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.reload();await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(page.getByLabel('Favori kıyılar')).toContainText('Trabzon');await page.getByText(/Av günlüğüm · 1 kayıt/).click();await expect(page.locator('.journal-entry')).toContainText('Trabzon');await expect(page.locator('.journal-entry')).toContainText('Spin denemesi');await page.locator('.journal-entry').getByRole('button',{name:/av kaydını sil/}).click();await expect(page.locator('.journal-entry')).toHaveCount(0);
});
test('category sheets, visible location and compact weather work with keyboard and back',async({page})=>{
 await sources(page);await page.addInitScript(()=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.86,lng:30.64,mode:'manual',savedAt:Date.now()})));await page.goto('/');await expect(page.locator('.location-status')).toContainText('Konyaaltı, Antalya');await expect(page.getByLabel('Konumuna göre hava özeti')).toContainText('22 °C');await expect(page.getByLabel('Konumuna göre hava özeti')).toContainText('UV 5,4');await page.getByRole('button',{name:'Tüm kategorileri aç',exact:true}).click();const sheet=page.getByRole('dialog',{name:'Tüm kategoriler',exact:true});await expect(sheet).toBeVisible();await page.keyboard.press('Escape');await expect(sheet).not.toBeVisible();await page.getByRole('button',{name:'Tüm kategorileri aç',exact:true}).click();await sheet.getByRole('button',{name:'Market',exact:true}).click();await expect(sheet).not.toBeVisible();await page.route('**/api/prices?**',r=>r.fulfill({json:{products:[],alternatives:[],depotCount:0,total:0,hasMore:false,radius:3}}));await page.getByRole('button',{name:'Ürün fiyatları',exact:true}).click();await page.getByRole('button',{name:'Diğer kategoriler',exact:true}).click();const categories=page.getByRole('dialog',{name:'Ürün kategorileri',exact:true});await categories.getByRole('button',{name:'Temizlik',exact:true}).click();await expect(categories).not.toBeVisible();await expect(page.locator('.feature-categories').getByRole('button',{name:'Temizlik',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Diğer kategoriler',exact:true}).click();await page.goBack();await expect(categories).not.toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('storage failures do not claim favorites or journal records were saved',async({page})=>{
 await sources(page);await page.addInitScript(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('yakinim:fishing:'))throw new DOMException('Full','QuotaExceededError');return original.call(this,key,value);};});await page.goto('/');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await page.getByRole('button',{name:'Kıyıyı favorilere ekle'}).click();await expect(page.getByRole('button',{name:'Kıyıyı favorilere ekle'})).toHaveAttribute('aria-pressed','false');await expect(page.getByText('Favori bu cihazda saklanamadı.',{exact:true})).toBeVisible();await page.getByText(/Av günlüğüm · 0 kayıt/).click();await page.getByRole('button',{name:'Av kaydı ekle',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Av kaydı',exact:true});await dialog.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Bu cihazda kayıt saklanamadı.');await expect(dialog).toBeVisible();
});

test('a map-picked coast is used for the returned fishing forecast',async({page})=>{
 await sources(page);await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#f7f5f1'}}]}}));await page.goto('/?preview');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await page.getByRole('button',{name:/Konyaaltı.*Kıyı seç/}).click();await page.getByRole('dialog',{name:'Kıyı seç',exact:true}).getByRole('button',{name:'Haritadan kıyı seç',exact:true}).click();await expect(page.getByText('Haritada istediğin noktaya dokun',{exact:true})).toBeVisible();const canvas=page.locator('.maplibregl-canvas');await expect(canvas).toBeVisible();const box=await canvas.boundingBox();if(!box)throw Error('No map canvas');await canvas.click({position:{x:box.width/2,y:box.height/2}});await expect(page.locator('.shore-select')).toContainText('Seçtiğim kıyı');await expect(page.locator('.forecast-metrics')).toBeVisible();await expect(page.locator('.maplibregl-canvas')).toHaveCount(0);
});
test('missing weather is identified and is not shown as zero wind',async({page})=>{
 await sources(page);await page.route('**/api/fishing?**',r=>{const data=richForecast();return r.fulfill({json:{...data,hourly:data.hourly.map(h=>({...h,wind:null,gust:null,airTemperature:null,feelsLike:null})),daily:[],partial:true,sourceAvailability:{weather:false,marine:true}}});});await page.goto('/');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(page.getByText('Deniz tahmini mevcut; hava tahmini alınamadı.',{exact:true})).toBeVisible();await expect(page.locator('.forecast-metrics')).toContainText('RüzgârVeri yok');await expect(page.locator('.forecast-metrics')).not.toContainText('0 m/sn');await expect(page.locator('.forecast-metrics')).toContainText('Dalga0,3 m');
});
