import {test,expect} from '@playwright/test';
test('fishing works without GPS and changes the coastal forecast',async({page})=>{
 const now=Math.floor(Date.now()/1000);const requests:string[]=[];
 await page.route('**/api/fishing?**',r=>{requests.push(r.request().url());return r.fulfill({json:{hourly:[{time:now,wind:0,gust:4,rain:10,wave:null,period:null,temperature:24,windDirection:90,waveDirection:null,pressure:1010}],daily:[{time:now,sunrise:now-3600,sunset:now+3600,moonPhase:.5}],partial:true,fetchedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+900000).toISOString()}});});
 await page.goto('/');await page.getByRole('button',{name:'Balıkçılık',exact:true}).click();await expect(page.getByRole('heading',{name:'Kıyı balıkçılığı'})).toBeVisible();await expect(page.locator('.fishing-hour')).toContainText('Rüzgâr 0 m/sn');await expect(page.locator('.fishing-hour')).toContainText('Dalga Veri yok');await page.getByRole('button',{name:'Alanya',exact:true}).click();await expect.poll(()=>requests.some(u=>u.includes('lng=32'))).toBe(true);await expect(page.getByRole('heading',{name:'Alanya',exact:true})).toBeVisible();await page.getByRole('button',{name:'Spin',exact:true}).click();await expect(page.getByText(/Atış alanını/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('price categories compare identical products separately from alternatives',async({page})=>{
 const urls:string[]=[];const offer=(market:string,price:number)=>({id:market,name:market,market,lat:36.88,lng:30.70,distanceM:100,price,unitPrice:'TL/L',updatedAt:new Date().toISOString(),promotion:null});
 await page.addInitScript(()=>localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.884,lng:30.704,savedAt:Date.now()})));
 await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[]}}));await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));
 await page.route('**/api/prices?**',r=>{urls.push(r.request().url());return r.fulfill({json:{products:[{id:'same',title:'Pınar Süt',quantity:'1 L',offers:[offer('migros',50),offer('bim',60)]}],alternatives:[{id:'other',title:'Başka Süt',quantity:'500 ML',offers:[offer('sok',30)]}],depotCount:3,total:2,hasMore:false,radius:3}});});
 await page.goto('/');await page.getByRole('button',{name:'Market',exact:true}).click();await page.getByRole('button',{name:'Ürün fiyatları',exact:true}).click();await page.getByRole('button',{name:'Süt ve süt ürünleri',exact:true}).click();await expect.poll(()=>urls.some(u=>u.includes('category=dairy'))).toBe(true);await expect(page.getByRole('heading',{name:'Aynı ürün, farklı marketler'})).toBeVisible();await expect(page.locator('.price-difference')).toContainText('%20');await expect(page.getByRole('heading',{name:'Alternatif ürünler'})).toBeVisible();await expect(page.locator('.product-price-card')).toHaveCount(2);await page.getByRole('button',{name:'Et ve balık',exact:true}).click();await expect.poll(()=>urls.some(u=>u.includes('category=meat-fish'))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
