import {test,expect} from '@playwright/test';
const mobileNav=(page:any)=>page.locator('.shell-nav--mobile');
test.beforeEach(async({page})=>{
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#eef5e7'}}]}}));
 await page.route('**/api/location?**',r=>r.fulfill({json:{label:'Antalya',province:'Antalya'}}));
 await page.route('**/api/viewport?**',r=>r.fulfill({json:{elements:[{type:'node',id:1,lat:36.884,lon:30.704,tags:{shop:'supermarket',name:'Kaydedilen Market'}}]}}));
 await page.route('**/api/overture?**',r=>r.fulfill({json:{places:[]}}));await page.route('**/api/nearby?**',r=>r.fulfill({json:{elements:[],places:[]}}));
});
test('four tabs keep services and media accessible without traffic',async({page})=>{
 let traffic=0;page.on('request',r=>{if(r.url().includes('/api/traffic'))traffic++;});await page.goto('/?preview');await expect(mobileNav(page).getByRole('button')).toHaveCount(4);await mobileNav(page).getByRole('button',{name:'Hizmetler'}).click();await expect(page.locator('.shell-service-grid>button')).toHaveCount(3);await expect(page.getByRole('button',{name:'Trafik',exact:true})).toHaveCount(0);await expect(page.getByRole('textbox',{name:'Yer ara'})).toBeVisible();await mobileNav(page).getByRole('button',{name:'Diğer'}).click();await expect(page.locator('.shell-service-grid>button')).toHaveCount(3);expect(traffic).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('saved place survives reload and can be removed',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('yakinim:v2:last-location'))localStorage.setItem('yakinim:v2:last-location',JSON.stringify({lat:36.884,lng:30.704,mode:'manual',savedAt:Date.now()}));});await page.goto('/');await mobileNav(page).getByRole('button',{name:'Hizmetler'}).click();await page.locator('.service-category-grid').getByRole('button',{name:'Marketler',exact:true}).click();await page.locator('.place-row').click();await page.getByRole('button',{name:'Yeri kaydet',exact:true}).click();await page.getByRole('button',{name:'Kapat',exact:true}).click();await mobileNav(page).getByRole('button',{name:'Kaydedilen'}).click();await expect(page.locator('.shell-saved-place')).toContainText('Kaydedilen Market');await page.reload();await mobileNav(page).getByRole('button',{name:'Kaydedilen'}).click();await expect(page.locator('.shell-saved-place')).toContainText('Kaydedilen Market');await page.getByRole('button',{name:'Kaydedilen Market kaydını kaldır'}).click();await expect(page.getByText('Henüz kaydedilen yer yok')).toBeVisible();
});
test('desktop and mobile both give Keşfet the full available map',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/?preview');await expect(page.locator('.shell-sidebar')).toBeVisible();await expect(page.locator('.maplibregl-canvas')).toBeVisible();await expect(page.locator('.place-row')).toHaveCount(0);const map=await page.locator('.map-canvas').boundingBox();expect(map!.x).toBe(230);expect(map!.width).toBe(1210);expect(map!.height).toBeGreaterThan(850);
 await page.setViewportSize({width:360,height:800});await expect(mobileNav(page)).toBeVisible();const mobile=await page.locator('.map-canvas').boundingBox();expect(mobile!.x).toBe(0);expect(mobile!.width).toBe(360);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('events change city and never manufacture dates or directions',async({page})=>{
 const cities:string[]=[];await page.route('**/api/events?**',r=>{const city=new URL(r.request().url()).searchParams.get('city')!;cities.push(city);return r.fulfill({json:{items:[{id:city,title:city==='7'?'Ankara etkinliği':'Antalya etkinliği',startsAt:null,endsAt:null,venue:null,source:'Etkinlik.io',url:'https://etkinlik.io/etkinlik/123/test'}],coverage:'Antalya',fetchedAt:new Date().toISOString(),partial:false}});});await page.goto('/?preview');await mobileNav(page).getByRole('button',{name:'Hizmetler'}).click();await page.getByRole('button',{name:'Etkinlikler',exact:true}).click();await expect(page.locator('.event-card')).toContainText('Antalya etkinliği');await page.getByLabel('Etkinlik şehri').selectOption('7');await expect(page.locator('.event-card')).toContainText('Ankara etkinliği');await expect(page.locator('.event-card')).toContainText('Tarih yok');await expect(page.getByRole('link',{name:'Yol tarifi',exact:true})).toHaveCount(0);expect(cities).toContain('8');expect(cities).toContain('7');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:1000});await expect(page.locator('.event-card')).toContainText('Ankara etkinliği');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
