import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=fs.readFileSync(new URL('../src/services/nearby-refresh.ts',import.meta.url),'utf8');
const box={exports:{}};
vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:box.exports,module:box});
const {shouldRefreshNearby,distanceMeters,NEARBY_REFRESH_DISTANCE_M}=box.exports;
const a={lat:36.947,lng:30.863};
const near={lat:36.9472,lng:30.863};
const far={lat:36.952,lng:30.863};
assert.equal(NEARBY_REFRESH_DISTANCE_M,500);
assert.ok(distanceMeters(a,near)<50);
assert.ok(distanceMeters(a,far)>500);
assert.equal(shouldRefreshNearby(null,a,'device',0,1000),true);
assert.equal(shouldRefreshNearby(a,near,'device',1000,40000),false);
assert.equal(shouldRefreshNearby(a,far,'device',1000,8000),false);
assert.equal(shouldRefreshNearby(a,far,'device',1000,24000),true);
assert.equal(shouldRefreshNearby(a,near,'manual',1000,1001),true);
assert.equal(shouldRefreshNearby(a,a,'manual',1000,1001),false);
console.log('Nearby tracking PASS: GPS motion does not refetch, 500m/20s throttling, manual override.');
