import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
const app=readFileSync('app.js','utf8');
let calls=[];
let replies=[];
const ctx=vm.createContext({URL,AbortController,setTimeout,clearTimeout,fetch:async url=>{calls.push(String(url));const r=replies.shift();if(r instanceof Error)throw r;return r;}});
vm.runInContext('const OVERPASS_ENDPOINTS=["https://first.test/api", "https://second.test/api"];'+app.slice(app.indexOf('function buildNearbyQuery(')),ctx);
const ok=elements=>({ok:true,json:async()=>({elements})});
replies=[{ok:false,status:503},ok([{id:1}])];
assert.equal((await vm.runInContext('fetchNearbyPayload("test")',ctx)).elements.length,1);
assert.equal(calls.length,2);
assert.ok(calls[1].startsWith('https://second.test/'));
calls=[];replies=[{ok:true,json:async()=>({remark:'runtime error: timeout',elements:[]})},ok([])];
await vm.runInContext('fetchNearbyPayload("test")',ctx);assert.equal(calls.length,2);
calls=[];replies=[new Error('Network error'),new Error('Network error')];
await assert.rejects(vm.runInContext('fetchNearbyPayload("test")',ctx));
replies=[ok([])];calls=[];await vm.runInContext('fetchNearbyPayload("test")',ctx);assert.equal(calls.length,1);
const query=vm.runInContext('buildNearbyQuery({lat:36.89,lng:30.70},1000)',ctx);
assert.equal((query.match(/around:1000,/g)||[]).length,3);assert.ok(!query.includes('5000'));
console.log('Network behavior: PASS (failover, partial response, failure, empty success, selected radius)');
