import assert from 'node:assert/strict';
import transit from '../lib/transit.cjs';
import events from '../lib/events.cjs';
const now=Date.parse('2026-10-08T22:18:23+03:00');
const data={result:{dateTime:'20261008221823'},busList:[{busId:'75805',displayRouteCode:'AC03',headSign:'MINICITY - AKSU',direction:'1',timeDiff:'6',stopDiff:'5',lat:'36.897068',lng:'30.669865'},{busId:'bad',timeDiff:'',lat:'36.9',lng:'30.7'}]};
const normalized=transit.normalizeArrivals(data,now);assert.equal(normalized.fresh,true);assert.equal(normalized.buses.length,1);assert.equal(normalized.buses[0].direction,1);assert.equal(normalized.buses[0].minutes,6);assert.equal(transit.normalizeArrivals(data,now+181000).fresh,false);assert.equal(transit.normalizeArrivals({...data,result:{}},now).fresh,false);
const route=transit.normalizePath({pathList:[{headSign:'SARISU - GÜZELOBA',busStopList:[{stopId:'13001',stopName:'SARISU',lat:'36.83',lng:'30.59',routes:'KL08,VS18'},{stopId:'13002',stopName:'Invalid',lat:'',lng:'30.6'}]}]},'KL08',0);assert.equal(route.stops.length,1);assert.deepEqual(route.stops[0].routes,['KL08','VS18']);
const html='<title>16. Antalya Kitap Fuarı 2026</title><p>2–11 Ekim 2026, Cam Piramit Fuar ve Kongre Merkezi, 10:00–20:00</p><img src="/logo.png" alt="Antalya Kitap Fuarı"><img src="/poster.jpg" alt="16. Antalya Kitap Fuarı"><a href="https://www.google.com/maps/dir/?api=1&amp;destination=Cam+Piramit">Yol</a>';
const [event]=events.parseBookFair(html,now);assert.equal(event.startsAt,'2026-10-02T10:00:00+03:00');assert.equal(event.endsAt,'2026-10-11T20:00:00+03:00');assert.equal(event.imageUrl,'https://kitapfuari.antalya.bel.tr/poster.jpg');assert.equal(event.price,null);assert.equal(new URL(event.directionsUrl).searchParams.get('destination'),'Cam Piramit');assert.equal(events.parseBookFair(html,Date.parse('2026-10-12')).length,0);assert.throws(()=>events.parseBookFair('<title>Kitap Fuarı</title><p>2026</p>',now));assert.throws(()=>events.parseBookFair(html.replace('11 Ekim','32 Ekim'),now));
assert.equal((await import('../api/transit.js')).default instanceof Function,true);assert.equal((await import('../api/events.js')).default instanceof Function,true);
const blog='<h2 id="b1">Anadolu Ateşi</h2><p>Tarih: 6, 13, 20, 27 Ekim 2026</p><p>Yer: Aspendos Antik Tiyatro</p><p>Saat: 21:00</p><h2 id="b2">Hatalı kayıt</h2><p>Tarih: 32 Ekim 2026 Yer: Antalya Saat: 21:00</p>';
const blogItems=events.parseBubilet(blog,'https://www.bubilet.com.tr/blog/antalya/test','theatre',now);
assert.equal(blogItems.length,3);assert.equal(blogItems[0].startsAt,'2026-10-13T21:00:00+03:00');assert.equal(events.deduplicate([...blogItems,...blogItems]).length,3);assert.equal(blogItems[0].directionsUrl,undefined);const [located]=events.locateEvents([{venue:'Antalya Bahçe'}]);assert.equal(new URL(located.directionsUrl).searchParams.get('destination'),'36.88178065,30.66679438');
const stops=await transit.query('stops',new URLSearchParams({lat:'36.9002946',lng:'30.7007151'}));
assert.equal(stops.stops[0].id,'11265');assert.equal(stops.stops[0].distanceM,0);assert.equal(stops.stops.some(s=>s.id==='11254'),true);assert.equal(stops.stops.filter(s=>s.name.includes('TONGUÇ')).length,10);assert.ok(stops.catalogSize>4000);assert.ok(stops.coverage.length>100);assert.ok(stops.stops.every((s,i,all)=>i===0||all[i-1].distanceM<=s.distanceM));
const wide=await transit.query('stops',new URLSearchParams({bounds:'36.68,31.54,36.74,31.59'}));
assert.equal(wide.scope,'viewport');
assert.ok(wide.stops.some(s=>s.id==='46237'),'Viewport map includes Manavgat stops far beyond current 2-km search');
const globalStop=await transit.query('stops',new URLSearchParams({q:'46237'}));
assert.equal(globalStop.scope,'search');
assert.ok(globalStop.stops.some(s=>s.id==='46237'));
await assert.rejects(transit.query('stops',new URLSearchParams({bounds:'36.8,30.7,36.7,30.8'})),/invalid_bounds/);
console.log('Full-region transit PASS: map viewport, global stop search and bounds validation.');
console.log('Antalya pilot PASS: fresh/stale arrivals, directions, valid stops, verified dates, expired events and source links.');

const locatedVenues=events.locateEvents([{venue:'Rockbull Performance Hall'},{venue:'Aspendos Antik Tiyatro'},{venue:'Manavgat Atatürk Kültür Merkezi'},{venue:'Konyaaltı Belediyesi Nazım Hikmet Fuar ve Kongre Merkezi'},{venue:'Antalya AKM Aspendos Salonu'}]);assert.ok(locatedVenues.every(v=>v.directionsUrl&&v.locationSource));
