import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import './transit-distance.mjs';
const read=path=>fs.readFileSync(path,'utf8');
const screen=read('src/components/PilotViews.tsx');
const list=read('src/components/TransitArrivals.tsx');
const map=read('src/components/TransitRouteView.tsx');
const sheet=read('src/components/FeatureSheet.tsx');
const css=read('src/model1.css');
const api=read('lib/transit.cjs');
assert.match(list,/onRoute\?\.\(bus\.code,bus\.direction,bus\.id\)/,'Bus identity must be sent to route map');
assert.match(screen,/vehicleId=\{route\.vehicleId\}/,'Route view should receive selected bus identity');
assert.match(screen,/onBack=\{\(\)=>setRoute\(null\)\}/,'Back should preserve selected stop');
assert.match(screen,/title=\{route\?\.code\|\|selected\?\.name/,'Route reuses original stop sheet');
assert.match(sheet,/back\?:boolean/,'Back arrow should be available');
assert.match(map,/refetchInterval:vehicleId\?20000:false/,'Vehicle position should poll every 20 seconds');
assert.doesNotMatch(map,/onDirectionChange|transit-route-directions|Hat yönü/,'Selected bus must not switch direction and lose its identity');
assert.doesNotMatch(screen,/onDirectionChange/,'The parent must preserve the selected bus identity until leaving the route');
assert.match(screen,/key=\{route\.code\+':'\+route\.direction\+':'\+\(route\.vehicleId\|\|'\'\)\}/,'Selected bus key must remain stable while the route is open');
assert.match(map,/\{vehicleId\?'Otomatik yenileme: 20 sn':''\}/,'Do not promise automatic live updates for route-only view');
assert.match(map,/arrivals\.data\.buses\.find\(b=>b\.id===vehicleId/,'Must track exact selected vehicle, not any bus on route');
assert.match(map,/!arrivals\.data\?\.fresh/,'Must distinguish stale source data');
assert.match(map,/is-last-seen/,'Old positions must not appear live');
assert.match(map,/requestAnimationFrame\(animate\)/,'Position updates should animate when plausible');
assert.match(map,/onClick=\{\(\)=>\{void path\.refetch\(\);if\(vehicleId\)void arrivals\.refetch\(\);\}\}/,'Manual refresh should update both');
assert.match(map,/map\.addLayer\(\{id:'transit-route-line'/,'Draw actual provider route geometry');
assert.match(map,/map\.addLayer\(\{id:'transit-route-stops'/,'Show clickable stops');
assert.match(map,/map\.fitBounds\(/,'Zoom to the route');
assert.match(css,/feature-dialog:has\(\.transit-route-view\)/,'Route view must fit mobile screen');
assert.match(api,/pointList/,'Provider must supply route geometry');
assert.match(api,/busId/,'Provider must supply vehicle identity');
assert.match(map,/transit-selected-stop-marker/,'Chosen stop must be marked on the route map');
assert.match(map,/transit-selected-stop-card/,'Selected stop must be identified by name');
assert.match(map,/distanceAlongRouteMeters/,'Distance should follow provider route shape when possible');
assert.match(map,/kuş uçuşu/,'Fallback distance must be labelled honestly');
assert.match(map,/compactCredits/,'Attribution should start collapsed');
assert.match(map,/creditsOpened/,'Users must be able to reopen map attribution');
assert.match(css,/transit-selected-stop-dot/,'Selected stop must use a visually distinct marker');
const p=JSON.parse(read('package.json'));assert.ok(p.scripts.build.includes('tests/transit-route.mjs'));
console.log('Transit route map PASS: bus identity, stop return, line geometry, active/stale states, automatic/manual refresh, mobile sheet.');
