import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=path=>fs.readFileSync(path,'utf8');
const screen=read('src/components/PilotViews.tsx');
const list=read('src/components/TransitArrivals.tsx');
const map=read('src/components/TransitRouteView.tsx');
const sheet=read('src/components/FeatureSheet.tsx');
const css=read('src/model1.css');
const api=read('lib/transit.cjs');
assert.match(list,/onRoute\?\.\(bus\.code,bus\.direction,bus\.id\)/,'Bus identity must be sent to route map');
assert.match(screen,/vehicleId\}\)\/?>/,'Route view should receive selected bus identity');
assert.match(screen,/onBack=\{\(\)=>setRoute\(null\)\}/,'Back should preserve selected stop');
assert.match(screen,/title=\{route\?\.code\|\|selected\?\.name/,'Route reuses original stop sheet');
assert.match(sheet,/back\?:boolean/,'Back arrow should be available');
assert.match(map,/refetchInterval:vehicleId\?20000:false/,'Vehicle position should poll every 20 seconds');
assert.match(map,/arrivals\.data\.buses\.find\(b=>b\.id===vehicleId/,'Must track exact selected vehicle, not any bus on route');
assert.match(map,/!arrivals\.data\?\.fresh/,'Must distinguish stale source data');
assert.match(map,/is-last-seen/,'Old positions must not appear live');
assert.match(map,/requestAnimationFrame\(animate\)/,'Position updates should animate when plausible');
assert.match(map,/onClick=\{\(\)=>\{void path\.refetch\(\);if\(vehicleId\)void arrivals\.refetch\(\);\}\}/,'Manual refresh should update both');
assert.match(map,/map\.addLayer\(\{id:'transit-route-line'/,'Draw actual provider route geometry');
assert.match(map,/map\.addLayer\(\{id:'transit-route-stops'/,'Show clickable stops');
assert.match(map,/map\.fitBounds\(/,'Zoom to the route');
assert.match(css,/feature-dialog:has\(\.transit-route-view\)/,'Route view must fit mobile screen');
assert.match(api,/pointList/,'Provider must supply route geometry');
assert.match(api,/busId/,'Provider must supply vehicle identity');
const p=JSON.parse(read('package.json'));assert.ok(p.scripts.build.includes('tests/transit-route.mjs'));
console.log('Transit route map PASS: bus identity, stop return, line geometry, active/stale states, automatic/manual refresh, mobile sheet.');
