const PARKS='https://api.ibb.gov.tr/ispark/Park';
const TOILETS='https://data.ibb.gov.tr/dataset/8789b75c-bae9-4acb-8287-bfc0ba88c8ea/resource/9585ab4a-d160-4541-8a41-b86eeec4c1cc/download/sehir_tuvaletleri_verisi.geojson';
const cache=new Map(),pending=new Map();
const text=x=>String(x??'').replace(/\s+/g,' ').trim().slice(0,180);
const number=x=>x==null||!['number','string'].includes(typeof x)||String(x).trim()===''?null:Number.isFinite(Number(x))?Number(x):null;
const point=(lat,lng)=>Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=40.5&&lat<=41.8&&lng>=27.5&&lng<=30.5;
const count=x=>{const n=number(x);return n!=null&&n>=0&&Number.isInteger(n)?n:null;};
function distance(a,b){const r=Math.PI/180,h=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lng-a.lng)*r/2)**2;return Math.round(12742000*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)));}
async function read(url,fetcher=fetch){const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);try{const r=await fetcher(url,{signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error('upstream_'+r.status);return await r.json();}finally{clearTimeout(timer);}}
async function cached(key,ttl,load){const hit=cache.get(key);if(hit&&Date.now()<hit.expires)return hit.data;if(pending.has(key))return pending.get(key);const promise=load().then(data=>{cache.set(key,{data,expires:Date.now()+ttl});if(cache.size>80)cache.delete(cache.keys().next().value);return data;}).finally(()=>pending.delete(key));pending.set(key,promise);return promise;}
function parksFromRows(rows,fetchedAt){if(!Array.isArray(rows))throw Error('invalid_parks');return rows.flatMap(row=>{const lat=number(row.lat),lng=number(row.lng),id=text(row.parkID);if(!point(lat,lng)||!/^\d+$/.test(id))return [];const total=count(row.capacity),rawFree=count(row.emptyCapacity),free=total!=null&&rawFree!=null&&rawFree<=total?rawFree:null;return [{id:'ibb:park:'+id,name:text(row.parkName)||'İSPARK',category:'parking',lat,lng,address:text(row.district)||'İstanbul',source:'İBB / İSPARK',licenseUrl:'https://data.ibb.gov.tr/license',facts:[text(row.parkType),row.workHours?'Saatler: '+text(row.workHours):''].filter(Boolean),availability:{free,total,open:row.isOpen===1||row.isOpen==='1'?true:row.isOpen===0||row.isOpen==='0'?false:null,fetchedAt}}];});}
function toiletsFromGeojson(data){if(!Array.isArray(data?.features))throw Error('invalid_toilets');return data.features.flatMap((f,i)=>{const [lng,lat]=f.geometry?.coordinates||[],p=f.properties||{};if(f.geometry?.type!=='Point'||!point(lat,lng)||text(p.TUVALET_DURUM).toLocaleLowerCase('tr')!=='aktif')return [];return [{id:'ibb:toilet:'+lat.toFixed(6)+':'+lng.toFixed(6),name:text(p.MAHAL_ADI)||'Şehir tuvaleti',category:'toilets',lat,lng,address:text(p.ILCE)||'İstanbul',source:'İBB Açık Veri',licenseUrl:'https://data.ibb.gov.tr/license',facts:[text(p.TUVALET_TIP),text(p.BAKIM_ODASI).toLocaleLowerCase('tr')==='var'?'Bebek bakım odası':''].filter(Boolean)}];});}
async function municipal(location,kind,fetcher=fetch){if(!point(location.lat,location.lng))return {places:[],coverage:'İstanbul',source:'İBB Açık Veri',partial:false};const jobs=[];if(kind==='parking'||kind==='all')jobs.push(cached('parks',120000,async()=>parksFromRows(await read(PARKS,fetcher),new Date().toISOString())));if(kind==='toilets'||kind==='all')jobs.push(cached('toilets',86400000,async()=>toiletsFromGeojson(await read(TOILETS,fetcher))));const results=await Promise.allSettled(jobs);if(results.every(r=>r.status==='rejected'))throw Error('municipal_unavailable');return {places:results.flatMap(r=>r.status==='fulfilled'?r.value:[]).map(p=>({...p,distanceM:distance(location,p)})).filter(p=>p.distanceM<=15000).sort((a,b)=>a.distanceM-b.distanceM),coverage:'İstanbul',source:'İBB Açık Veri',partial:results.some(r=>r.status==='rejected'),fetchedAt:new Date().toISOString()};}
function airFromData(data,now=Date.now()){if(data?.hourly_units?.time!=='unixtime'||!Array.isArray(data.hourly?.time))throw Error('invalid_air');const target=Math.floor(now/3600000)*3600,index=data.hourly.time.indexOf(target);if(index<0)throw Error('air_hour_missing');const units={pm2_5:'μg/m³',pm10:'μg/m³',european_aqi:'EAQI'};const values={};for(const [k,u] of Object.entries(units)){const n=data.hourly?.[k]?.[index];values[k]=data.hourly_units[k]===u&&typeof n==='number'&&Number.isFinite(n)&&n>=0?n:null;}if(Object.values(values).every(v=>v==null))throw Error('air_values_missing');return {...values,time:target,source:'CAMS / Open-Meteo',fetchedAt:new Date(now).toISOString(),model:true};}
async function air(location,fetcher=fetch){const lat=Math.round(location.lat*100)/100,lng=Math.round(location.lng*100)/100,key=`air:${lat}:${lng}:${Math.floor(Date.now()/3600000)}`;return cached(key,900000,async()=>{const url='https://air-quality-api.open-meteo.com/v1/air-quality?'+new URLSearchParams({latitude:String(lat),longitude:String(lng),hourly:'pm2_5,pm10,european_aqi',timeformat:'unixtime',forecast_days:'2'});return airFromData(await read(url,fetcher));});}
module.exports={municipal,air,parksFromRows,toiletsFromGeojson,airFromData,_cache:cache};
