import {lazy,Suspense,useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {RefreshCw} from 'lucide-react';
import type {Coordinates} from '../types';
const OutageMap=lazy(()=>import('./OutageMap'));
const DiscoveryMap=lazy(()=>import('./MapView').then(m=>({default:m.MapView})));
export type Outage={id:string;district?:string;neighborhood?:string;startsAt:string;endsAt:string|null;message?:string;notification?:string;locations?:{district:string;neighborhood:string}[];geometry?:{type:'MultiPolygon';coordinates:number[][][][]};source:string;sourceUrl:string};
const date=(value:string)=>new Date(value).toLocaleString('tr-TR',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'});
const fold=(value:string)=>value.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
type TrafficIndex={available:boolean;index:number|null;observedAt:string|null;fresh:boolean;source:string;sourceUrl:string;licenseUrl:string};
export function TrafficView({location,search}:{location:Coordinates|null;search:string}){
 const center=location||{lat:36.8969,lng:30.7133};
 const traffic=useQuery({queryKey:['traffic-index',location?.lat,location?.lng],queryFn:async({signal})=>{const response=await fetch(`/api/traffic?lat=${location!.lat}&lng=${location!.lng}`,{signal});if(!response.ok)throw Error('traffic_unavailable');return response.json() as Promise<TrafficIndex>;},enabled:!!location,staleTime:60000,refetchInterval:60000,retry:0});
 return <section className="pilot-panel traffic-panel"><div className="pilot-title"><h2>Yol ve trafik</h2>{location&&<button aria-label="Trafik verisini yenile" disabled={traffic.isFetching} onClick={()=>void traffic.refetch()}><RefreshCw size={18}/></button>}</div><p>Keşif, ulaşım ve yol görünümünde aynı harita kullanılır.</p>
 {traffic.data?.available&&!traffic.isError&&<section className="traffic-index-card"><strong>İstanbul geneli trafik endeksi</strong>{traffic.data.fresh&&traffic.data.index!==null?<div className="traffic-index-value">{traffic.data.index}<small>/ 100</small></div>:<p role="status">Kaynak güncel değil; canlı endeks gösterilmiyor.</p>}<small>Şehir geneli ölçümdür; tek bir yolun yoğunluğunu göstermez.</small>{traffic.data.observedAt&&<small>Kaynak zamanı: {new Date(traffic.data.observedAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</small>}<a href={traffic.data.sourceUrl} target="_blank" rel="noreferrer">{traffic.data.source}</a><a href={traffic.data.licenseUrl} target="_blank" rel="noreferrer">Açık veri lisansı</a></section>}
 {traffic.isError&&<p role="alert">Trafik kaynağına ulaşılamadı. Yol haritası kullanılabilir.</p>}
 <div className="traffic-map"><Suspense fallback={<p>Harita hazırlanıyor…</p>}><DiscoveryMap location={center} places={[]} picking={false} onPick={()=>{}} onViewportChange={()=>{}} memoryKey={`traffic:${center.lat}:${center.lng}`}/></Suspense></div>
 <div className="traffic-source-actions"><small role="status">Bu görünüm yol haritasıdır. Yol üzerindeki canlı yoğunluk renkleri gösterilmez.</small>{!location?<small>Bölgenin veri durumunu görmek için bir konum seç.</small>:traffic.isPending?<small>Bu bölgenin trafik veri kapsamı kontrol ediliyor…</small>:traffic.data&&!traffic.data.available?<small>İBB açık trafik endeksi yalnızca İstanbul için kullanılabilir. Seçili bölge için doğrulanmış canlı trafik kaynağı henüz bağlı değil.</small>:null}{search.trim()&&<small>Cadde araması henüz desteklenmiyor; haritayı kaydırıp yakınlaştırabilirsin.</small>}</div></section>;
}

export function OutagesView({location,search}:{location:Coordinates|null;search:string}){
 const [kind,setKind]=useState<'water'|'electric'>('water'),[selected,setSelected]=useState<string|null>(null);
 const query=useQuery({queryKey:['outages',kind],queryFn:async({signal})=>{const r=await fetch(`/api/outages?kind=${kind}`,{signal});if(!r.ok)throw Error('source_unavailable');return r.json() as Promise<{items:Outage[];fetchedAt:string;partial:boolean;source?:string}>;},staleTime:60000,refetchInterval:300000,retry:1});
 const items=(query.data?.items||[]).filter(item=>{const names=kind==='water'?[{district:item.district||'',neighborhood:item.neighborhood||''}]:item.locations||[];return !search||fold(names.map(l=>`${l.district} ${l.neighborhood}`).join(' ')+' '+(item.message||'')).includes(fold(search));});
 useEffect(()=>{if(selected&&!items.some(i=>i.id===selected))setSelected(null);},[query.data,search,selected]);
 return <section className="pilot-panel"><div className="pilot-title"><h2>Kesintiler</h2><button aria-label="Kesintileri yenile" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw size={18}/></button></div><div className="pharmacy-filter"><button aria-pressed={kind==='water'} onClick={()=>{setKind('water');setSelected(null);}}>Su</button><button aria-pressed={kind==='electric'} onClick={()=>{setKind('electric');setSelected(null);}}>Elektrik</button></div>{query.isPending&&<p role="status">Yükleniyor…</p>}{query.isError&&<div className="pilot-error" role="alert"><p>Kesintiler alınamadı.</p><button className="plain-button" onClick={()=>void query.refetch()}>Tekrar dene</button></div>}{query.data&&!query.isError&&<>{query.data.partial&&<p role="status">Bazı kesinti bilgileri alınamadı; liste ve mahalle araması eksik olabilir.</p>}<small className="data-note">Kaynak: {query.data.source|| (kind==='water'?'SuKesintileri.com.tr':'AEDAŞ / CK Enerji')} · Son veri alımı: {new Date(query.data.fetchedAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})} · Durumu sağlayıcıdan doğrulayın.</small>{!items.length&&<small>{query.data.partial?'Eksik veride eşleşme bulunamadı.':'Kayıt yok.'}</small>}{items.map(item=><article className="outage-card" key={item.id}><h3>{kind==='water'?item.neighborhood:item.locations?.map(l=>l.neighborhood).filter((n,i,a)=>a.indexOf(n)===i).join(' · ')||'Elektrik kesintisi'}</h3><small>{kind==='water'?item.district:item.locations?.map(l=>l.district).filter((n,i,a)=>a.indexOf(n)===i).join(' · ')}</small><p>{date(item.startsAt)}{item.endsAt&&` · Tahmini bitiş: ${date(item.endsAt)}`}</p>{item.message&&<p>{item.message}</p>}{kind==='electric'&&!!item.geometry?.coordinates.length&&<><button className="plain-button" onClick={()=>setSelected(selected===item.id?null:item.id)}>{selected===item.id?'Haritayı kapat':'Etkilenen alanı göster'}</button>{selected===item.id&&<Suspense fallback={<p>Harita hazırlanıyor…</p>}><OutageMap items={[item]} location={location} selected={item.id} onSelect={setSelected}/></Suspense>}</>}</article>)}</>}</section>;
}
