import {lazy,Suspense,useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {RefreshCw} from 'lucide-react';
import type {Coordinates} from '../types';
const OutageMap=lazy(()=>import('./OutageMap'));
export type Outage={id:string;district?:string;neighborhood?:string;startsAt:string;endsAt:string|null;message?:string;notification?:string;locations?:{district:string;neighborhood:string}[];geometry?:{type:'MultiPolygon';coordinates:number[][][][]};source:string;sourceUrl:string};
const date=(value:string)=>new Date(value).toLocaleString('tr-TR',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'});
const fold=(value:string)=>value.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
export function TrafficView({location,search}:{location:Coordinates|null;search:string}){
 const center=location||{lat:36.8969,lng:30.7133};const [version,setVersion]=useState(0),[loaded,setLoaded]=useState(false);
 useEffect(()=>setLoaded(false),[version,center.lat,center.lng]);
 const [term,setTerm]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>setTerm(search.trim()),600);return()=>clearTimeout(timer);},[search]);
 const params=new URLSearchParams({ll:`${center.lng},${center.lat}`,z:'14',l:'map,trf',lang:'tr_TR'});if(term.length>=2){params.set('mode','search');params.set('text',term);}
 const url=`https://yandex.com.tr/map-widget/v1/?${params}`;
 return <section className="pilot-panel traffic-panel"><div className="pilot-title"><h2>Trafik yoğunluğu</h2><button aria-label="Trafik haritasını yenile" onClick={()=>setVersion(v=>v+1)}><RefreshCw size={18}/></button></div><div className="traffic-map">{!loaded&&<p role="status" className="traffic-loading">Trafik haritası yükleniyor…</p>}<iframe key={version} title="Canlı trafik haritası" src={url} onLoad={()=>setLoaded(true)} allow="geolocation https://yandex.com.tr" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/></div><div className="traffic-legend" aria-label="Trafik renkleri"><span><i className="traffic-free"/>Akıcı</span><span><i className="traffic-slow"/>Yavaş</span><span><i className="traffic-busy"/>Yoğun</span></div></section>;
}
export function OutagesView({location,search}:{location:Coordinates|null;search:string}){
 const [kind,setKind]=useState<'water'|'electric'>('water'),[selected,setSelected]=useState<string|null>(null);
 const query=useQuery({queryKey:['outages',kind],queryFn:async({signal})=>{const r=await fetch(`/api/outages?kind=${kind}`,{signal});if(!r.ok)throw Error('source_unavailable');return r.json() as Promise<{items:Outage[];fetchedAt:string;partial:boolean}>;},staleTime:60000,refetchInterval:300000,retry:1});
 const items=(query.data?.items||[]).filter(item=>{const names=kind==='water'?[{district:item.district||'',neighborhood:item.neighborhood||''}]:item.locations||[];return !search||fold(names.map(l=>`${l.district} ${l.neighborhood}`).join(' ')+' '+(item.message||'')).includes(fold(search));});
 useEffect(()=>{if(selected&&!items.some(i=>i.id===selected))setSelected(null);},[query.data,search,selected]);
 return <section className="pilot-panel"><div className="pilot-title"><h2>Kesintiler</h2><button aria-label="Kesintileri yenile" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw size={18}/></button></div><div className="pharmacy-filter"><button aria-pressed={kind==='water'} onClick={()=>{setKind('water');setSelected(null);}}>Su</button><button aria-pressed={kind==='electric'} onClick={()=>{setKind('electric');setSelected(null);}}>Elektrik</button></div>{query.isPending&&<p role="status">Yükleniyor…</p>}{query.isError&&<div className="pilot-error" role="alert"><p>Kesintiler alınamadı.</p><button className="plain-button" onClick={()=>void query.refetch()}>Tekrar dene</button></div>}{query.data&&!query.isError&&<>{!items.length&&<small>Kayıt yok.</small>}{items.map(item=><article className="outage-card" key={item.id}><h3>{kind==='water'?item.neighborhood:item.locations?.map(l=>l.neighborhood).filter((n,i,a)=>a.indexOf(n)===i).join(' · ')||'Elektrik kesintisi'}</h3><small>{kind==='water'?item.district:item.locations?.map(l=>l.district).filter((n,i,a)=>a.indexOf(n)===i).join(' · ')}</small><p>{date(item.startsAt)}{item.endsAt&&` · Tahmini bitiş: ${date(item.endsAt)}`}</p>{item.message&&<p>{item.message}</p>}{kind==='electric'&&!!item.geometry?.coordinates.length&&<><button className="plain-button" onClick={()=>setSelected(selected===item.id?null:item.id)}>{selected===item.id?'Haritayı kapat':'Etkilenen alanı göster'}</button>{selected===item.id&&<Suspense fallback={<p>Harita hazırlanıyor…</p>}><OutageMap items={[item]} location={location} selected={item.id} onSelect={setSelected}/></Suspense>}</>}</article>)}</>}</section>;
}
