import {useState,type FormEvent} from 'react';
import {FeatureSheet} from './FeatureSheet';
import {readJournal,saveJournal,type CatchEntry,type Shore} from '../services/fishing-storage';
import {clock,dayKey,measure,type ForecastHour} from '../services/forecast';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export default function FishingJournal({shore,hour,fetchedAt}:{shore:Shore;hour?:ForecastHour;fetchedAt?:string}){
 const [entries,setEntries]=useState(readJournal),[open,setOpen]=useState(false),[message,setMessage]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),date=String(values.get('date')),count=Number(values.get('count')),minutes=Number(values.get('minutes'));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date>today()||!Number.isInteger(count)||count<0||count>999||!Number.isInteger(minutes)||minutes<0||minutes>1440){setMessage('Tarih, adet ve süreyi kontrol et.');return;}
  const entry:CatchEntry={id:crypto.randomUUID(),date,shore:{...shore},method:values.get('method')==='spin'?'spin':'yemli',species:String(values.get('species')||'').trim().slice(0,80),count,minutes,note:String(values.get('note')||'').trim().slice(0,500),forecast:hour&&fetchedAt&&date===dayKey(hour.time)?{time:hour.time,wave:hour.wave??null,wind:hour.wind??null,fetchedAt}:null};
  const next=[entry,...entries].slice(0,200);if(!saveJournal(next)){setMessage('Bu cihazda kayıt saklanamadı. Tarayıcının depolama ayarını kontrol et.');return;}setEntries(next);setOpen(false);setMessage('Av kaydı bu cihazda saklandı.');
 }
 function remove(id:string){const next=entries.filter(e=>e.id!==id);if(!saveJournal(next)){setMessage('Kayıt silinemedi; tarayıcı depolamasını kontrol et.');return;}setEntries(next);setMessage('Av kaydı silindi.');}
 return <details className="fishing-journal"><summary>Av günlüğüm · {entries.length} kayıt</summary><p className="feature-note">Kayıtlar ve kıyı noktaları yalnızca bu tarayıcıda saklanır. Tarayıcı verilerini temizlersen silinir; diğer cihazlara eşitlenmez. En son 200 kayıt tutulur.</p><button className="outline-button" onClick={()=>{setMessage('');setOpen(true);}}>Av kaydı ekle</button>{message&&<p role="status">{message}</p>}{entries.map(e=><article className="journal-entry" key={e.id}><div className="row-between"><strong>{e.shore.name}</strong><button aria-label={`${e.date} av kaydını sil`} onClick={()=>remove(e.id)}>Sil</button></div><small>{e.date} · {e.method==='spin'?'Spin':'Yemli'} · {e.minutes} dk</small><p>{e.species||'Tür belirtilmedi'} · {e.count} adet</p>{e.note&&<p>{e.note}</p>}{e.forecast&&<small>Kayda eklenen bölgesel tahmin: {clock(e.forecast.time)} · Dalga {measure(e.forecast.wave,'m')} · Rüzgâr {measure(e.forecast.wind,'m/sn')} · Kıyı ölçümü değildir.</small>}</article>)}<FeatureSheet open={open} title="Av kaydı" onClose={()=>setOpen(false)}><form className="feature-form" onSubmit={submit}><strong>{shore.name}</strong><label>Tarih<input name="date" aria-label="Av tarihi" type="date" defaultValue={today()} max={today()} required/></label><label>Yöntem<select name="method"><option value="yemli">Yemli</option><option value="spin">Spin</option></select></label><label>Tür (isteğe bağlı)<input name="species" maxLength={80} placeholder="Örneğin levrek"/></label><div className="form-columns"><label>Adet<input name="count" type="number" min={0} max={999} defaultValue={0} required/></label><label>Süre (dakika)<input name="minutes" type="number" min={0} max={1440} defaultValue={60} required/></label></div><label>Not<textarea name="note" maxLength={500} rows={3}/></label><small>Varsa seçilen saatin model tahmini, aynı tarihteki kayda eklenir. Avın gerçek hava koşullarını temsil etmez.</small>{message&&<p role="alert">{message}</p>}<button className="solid-button" type="submit">Kaydı sakla</button></form></FeatureSheet></details>;
}
