import {useEffect,useRef,useState} from 'react';
import maplibregl from 'maplibre-gl';
import type {Coordinates} from '../types';
import type {Outage} from './CityServices';
export default function OutageMap({items,location,selected,onSelect}:{items:Outage[];location:Coordinates|null;selected:string|null;onSelect:(id:string)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<maplibregl.Map|null>(null),[ready,setReady]=useState(false),[failed,setFailed]=useState(false);const select=useRef(onSelect);select.current=onSelect;
 useEffect(()=>{if(!container.current)return;const m=new maplibregl.Map({container:container.current,style:'https://tiles.openfreemap.org/styles/positron',center:[location?.lng||30.7133,location?.lat||36.8969],zoom:11,attributionControl:{compact:true}});map.current=m;m.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');m.on('load',()=>{m.addSource('outages',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'outage-fill',type:'fill',source:'outages',paint:{'fill-color':'#c65b3d','fill-opacity':0.3}});m.addLayer({id:'outage-line',type:'line',source:'outages',paint:{'line-color':'#a94229','line-width':2}});m.on('click','outage-fill',e=>{const id=e.features?.[0]?.properties?.id;if(id)select.current(String(id));});m.on('mouseenter','outage-fill',()=>{m.getCanvas().style.cursor='pointer';});m.on('mouseleave','outage-fill',()=>{m.getCanvas().style.cursor='';});setReady(true);});m.on('error',()=>setFailed(true));if(location)new maplibregl.Marker({color:'#79576d'}).setLngLat([location.lng,location.lat]).addTo(m);const resize=new ResizeObserver(()=>m.resize());resize.observe(container.current);return()=>{resize.disconnect();m.remove();map.current=null;};},[]);
 useEffect(()=>{const m=map.current;if(!m||!ready)return;const features=items.filter(i=>i.geometry?.coordinates.length).map(i=>({type:'Feature' as const,properties:{id:i.id},geometry:i.geometry!}));(m.getSource('outages') as maplibregl.GeoJSONSource).setData({type:'FeatureCollection',features});m.setPaintProperty('outage-fill','fill-opacity',['case',['==',['get','id'],selected||''],0.55,0.25]);},[ready,items,selected]);
 useEffect(()=>{const m=map.current;if(!m||!ready||!selected)return;const coordinates=items.find(i=>i.id===selected)?.geometry?.coordinates.flat(2);if(!coordinates?.length)return;const bounds=new maplibregl.LngLatBounds();for(const point of coordinates)bounds.extend([point[0],point[1]]);m.fitBounds(bounds,{padding:35,maxZoom:15,duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:350});},[ready,selected]);
 return <div className="outage-map"><div ref={container} className="outage-map-canvas" aria-label="Elektrik kesintisi alanları"/>{failed&&<small className="outage-map-error">Haritanın bazı katmanları yüklenemedi.</small>}</div>;
}
