import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {keepPreviousData,useQuery} from '@tanstack/react-query';
import {ArrowLeft,ArrowUpRight,MapPin,Navigation,RefreshCw} from 'lucide-react';
import type {Coordinates,Place} from '../types';
const MapView=lazy(()=>import('./MapView').then(m=>({default:m.MapView})));

type Stop={id:string;name:string;lat:number;lng:number;routes:string[];distanceM:number};
type Bus={id:string;code:string;name:string;direction:number;minutes:number;stops:number|null};
type Event={id:string;title:string;startsAt:string;endsAt:string;hours:string|null;venue:string|null;imageUrl?:string;directionsUrl?:string;url:string;source:string;price:null;kind?:string;description?:string};
async function get<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal});if(!r.ok)throw new Error('Kaynak alınamadı');return r.json();}
const routeLink=(p:Coordinates)=>`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;
type PriceOffer={id:string;name:string;market:string;lat:number;lng:number;distanceM:number;price:number;unitPrice:string;updatedAt:string;promotion:string|null};
type PriceProduct={id:string;title:string;quantity:string;imageUrl?:string;offers:PriceOffer[]};
const marketNames:Record<string,string>={a101:'A101',bim:'BİM',sok:'ŞOK',migros:'Migros',carrefour:'CarrefourSA',hakmar:'Hakmar',tarimkredi:'Tarım Kredi',tarim_kredi:'Tarım Kredi'};
const money=(value:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value);
function PriceCard({product}:{product:PriceProduct}){
 const [expanded,setExpanded]=useState(false);const offers=expanded?product.offers:product.offers.slice(0,3);
 return <article className="product-price-card"><div className="product-price-heading">{product.imageUrl&&<img src={product.imageUrl} alt="" loading="lazy" onError={e=>{e.currentTarget.hidden=true;}}/>}<div><h3>{product.title}</h3><small>{product.quantity}</small></div></div>{offers.map((offer,i)=><div className="product-offer" key={offer.id}><div><strong>{marketNames[offer.market]||offer.market}</strong><span>{offer.name}</span><small>{offer.distanceM} m kuş uçuşu · {i===0?'En düşük fiyat':''}</small><small>Kaynak güncellemesi: {new Date(offer.updatedAt).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}</small>{offer.promotion&&<small>{offer.promotion}</small>}<a href={routeLink(offer)} target="_blank" rel="noreferrer">Şubeye yol tarifi</a></div><div className="offer-price"><strong>{money(offer.price)}</strong><small>{offer.unitPrice}</small></div></div>)}{product.offers.length>3&&<button className="plain-button" onClick={()=>setExpanded(!expanded)}>{expanded?'Daha az göster':`${product.offers.length} fiyat kaydının tamamı`}</button>}</article>;
}
export function ProductPrices({location}:{location:Coordinates|null}){
 const [input,setInput]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(input.trim());setPage(0);},450);return ()=>clearTimeout(timer);},[input]);
 useEffect(()=>setPage(0),[location?.lat,location?.lng]);
 const inArea=!!location&&location.lat>=36.7&&location.lat<=37.2&&location.lng>=30.3&&location.lng<=31.1;
 const prices=useQuery({queryKey:['prices',location?.lat,location?.lng,search,page],queryFn:({signal})=>get<{products:PriceProduct[];depotCount:number;total:number;hasMore:boolean;radius:number}>(`/api/prices?${new URLSearchParams({lat:String(location!.lat),lng:String(location!.lng),q:search,page:String(page)})}`,signal),enabled:inArea&&search.length>=2,staleTime:300000,retry:1});
 return <section className="pilot-panel"><div className="pilot-title"><h2>Ürün fiyatları</h2>{search.length>=2&&inArea&&<button aria-label="Fiyatları yenile" onClick={()=>void prices.refetch()} disabled={prices.isFetching}><RefreshCw size={18}/></button>}</div>{!location?<p>Yakındaki şube fiyatları için üstteki Konum düğmesini kullan.</p>:!inArea?<p>Ürün fiyatları şu an Antalya merkezde kullanılabilir.</p>:<><label className="search-box pilot-search"><input aria-label="Ürün ara" placeholder="Ürün veya marka ara" value={input} onChange={e=>setInput(e.target.value)} maxLength={80}/></label>{search.length<2?<p>Örneğin süt, kahve veya deterjan yaz.</p>:<>{prices.isPending&&<p role="status">Yakındaki şubelerin fiyatları yükleniyor…</p>}{prices.isError&&<Retry onClick={()=>void prices.refetch()}/>} {prices.data&&!prices.isError&&<><small>{prices.data.radius} km çevrede {prices.data.depotCount} şube · TÜBİTAK Market Fiyatı</small>{prices.data.products.length===0&&<p>{prices.data.depotCount?'Bu aramada yakındaki şubelerden güncel fiyat bulunamadı. Başka ürün veya marka deneyebilirsin.':'Bu konum çevresinde kaynakta kayıtlı şube bulunamadı.'}</p>}{prices.data.products.map(product=><PriceCard key={product.id} product={product}/>)}{(page>0||prices.data.hasMore)&&<div className="price-pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}>Önceki</button><span>{page+1}</span><button disabled={!prices.data.hasMore} onClick={()=>setPage(page+1)}>Sonraki</button></div>}<small>Fiyatlar kaynağın bildirdiği şubeye aittir; rafta farklı olabilir.</small></>}</>}</>}</section>;
}
export function TransitView({location}:{location:Coordinates|null}){
 const [selected,setSelected]=useState<Stop|null>(null),[map,setMap]=useState(false),[route,setRoute]=useState<{code:string;direction:number}|null>(null),[search,setSearch]=useState('');
 useEffect(()=>{setSelected(null);setRoute(null);},[location?.lat,location?.lng]);
 const inPilotArea=!!location&&location.lat>=36.7&&location.lat<=37.2&&location.lng>=30.3&&location.lng<=31.1;
 const coords=location?new URLSearchParams({lat:String(location.lat),lng:String(location.lng)}).toString():'';
 const stops=useQuery({queryKey:['transit-stops',location?.lat,location?.lng],queryFn:({signal})=>get<{stops:Stop[];coverage:string[];partial:boolean;catalogAt:string;catalogSize:number;stale:boolean}>(`/api/transit?${coords}`,signal),enabled:inPilotArea,staleTime:300000,retry:1,placeholderData:keepPreviousData});
 const buses=useQuery({queryKey:['transit-arrivals',selected?.id,location?.lat,location?.lng],queryFn:({signal})=>get<{buses:Bus[];fresh:boolean;sourceAt:string|null}>(`/api/transit?action=arrivals&stop=${selected!.id}&${coords}`,signal),enabled:!!selected&&!!location,refetchInterval:20000,retry:0});
 const path=useQuery({queryKey:['transit-route',route?.code,route?.direction],queryFn:({signal})=>get<{name:string;stops:Stop[]}>(`/api/transit?action=route&code=${encodeURIComponent(route!.code)}&direction=${route!.direction}&${coords}`,signal),enabled:!!route&&!!location,staleTime:3600000,retry:0});
 const filtered=(stops.data?.stops||[]).filter(s=>`${s.name} ${s.id} ${s.routes.join(' ')}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const places=useMemo(()=>filtered.map(s=>({id:`transit:${s.id}`,name:s.name,category:'transit',lat:s.lat,lng:s.lng,address:`Durak ${s.id} · ${s.routes.join(', ')}`,distanceM:s.distanceM,source:'Antalyakart / Kentkart'} satisfies Place)),[stops.data,search]);
 if(!location)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Yakın duraklar için üstteki Konum düğmesini kullan.</p><small>Antalya merkez pilotu</small></section>;
 if(!inPilotArea)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Bu pilot Antalya merkezde kullanılabilir.</p></section>;
 if(route)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setRoute(null)}><ArrowLeft size={18}/>Durağa dön</button><h2>{route.code}</h2><p>{path.data?.name||'Güzergâh'}</p><div className="pharmacy-filter">{[0,1].map(direction=><button key={direction} aria-pressed={route.direction===direction} onClick={()=>setRoute({...route,direction})}>{direction===0?'Gidiş':'Dönüş'}</button>)}</div>{path.isPending&&<p role="status">Duraklar yükleniyor…</p>}{path.isError&&<Retry onClick={()=>void path.refetch()}/>}<ol className="route-stops">{path.data?.stops.map(s=><li key={s.id}>{s.name}<small>{s.id}</small></li>)}</ol></section>;
 if(selected)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setSelected(null)}><ArrowLeft size={18}/>Duraklar</button><div className="pilot-title"><h2>{selected.name}</h2><button aria-label="Otobüsleri yenile" onClick={()=>void buses.refetch()} disabled={buses.isFetching}><RefreshCw size={18}/></button></div><small>Durak {selected.id} · Antalyakart / Kentkart</small><a className="outline-button pilot-directions" href={routeLink(selected)} target="_blank" rel="noreferrer"><Navigation size={16}/>Durağa yol tarifi</a><div className="stop-route-list"><small>Bu duraktan geçen hatlar</small><div className="pharmacy-filter">{selected.routes.map(code=><button key={code} onClick={()=>setRoute({code,direction:0})}>{code}</button>)}</div></div>{buses.isPending&&<p role="status">Yaklaşan araçlar yükleniyor…</p>}{buses.isError&&<Retry onClick={()=>void buses.refetch()}/>}<small className="pilot-updated">{buses.data?.sourceAt&&`Kaynak: ${new Date(buses.data.sourceAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}`}</small>{buses.data&&!buses.data.fresh&&<p role="alert">Kaynak güncel değil. Geliş tahminleri gösterilmiyor.</p>}{buses.data?.fresh&&buses.data.buses.length===0&&<p>Kaynak şu an yaklaşan araç bildirmiyor.</p>}{buses.data?.fresh&&!buses.isError&&buses.data.buses.map(b=><button className="bus-row" key={b.id} onClick={()=>setRoute({code:b.code,direction:b.direction})}><strong>{b.code}</strong><span>{b.name}<small>{b.stops===null?'':`${b.stops} durak uzakta`}</small></span><span className="bus-time">{b.minutes===0?'Yaklaşıyor':`${b.minutes} dk`}<small>Tahmini</small></span></button>)}</section>;
 return <section className="pilot-panel"><div className="pilot-title"><h2>Yakın duraklar</h2><button onClick={()=>setMap(!map)}><MapPin size={17}/>{map?'Liste':'Harita'}</button></div><small>Antalya · Konumuna en yakın duraklar</small><label className="search-box pilot-search"><input aria-label="Durak veya hat ara" placeholder="Durak veya hat ara" value={search} onChange={e=>setSearch(e.target.value)}/></label>{stops.isPending&&<p role="status">Duraklar yükleniyor…</p>}{stops.isError&&<Retry onClick={()=>void stops.refetch()}/>} {stops.data?.stale&&<small>Durak kataloğunun güncellenmesi gerekiyor.</small>}{stops.data?.partial&&<small>Durak kaynağında bazı güzergâhlar eksik.</small>}{map&&<div className="pilot-map"><Suspense fallback={<p>Harita hazırlanıyor…</p>}><MapView location={location} places={places} picking={false} onPick={()=>{}} onViewportChange={()=>{}} loading={stops.isFetching}/></Suspense></div>}{!stops.isPending&&stops.data&&!filtered.length&&<p>2 km içinde eşleşen durak bulunamadı.</p>}{filtered.map(s=><button className="stop-row" key={s.id} onClick={()=>setSelected(s)}><MapPin size={20}/><span><strong>{s.name}</strong><small>{s.id} · {s.distanceM} m kuş uçuşu</small><small>{s.routes.join(' · ')}</small></span></button>)}</section>;
}
function Retry({onClick}:{onClick:()=>void}){return <div className="pilot-error" role="alert"><p>Kaynak şu an alınamıyor.</p><button className="plain-button" onClick={onClick}>Tekrar dene</button></div>;}
export function EventsView(){
 const [filter,setFilter]=useState('all'),[kind,setKind]=useState('all');const events=useQuery({queryKey:['antalya-events'],queryFn:({signal})=>get<{items:Event[];coverage:string;fetchedAt:string;partial:boolean}>('/api/events',signal),staleTime:300000,refetchInterval:300000,retry:1});
 const now=Date.now();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const items=(events.data?.items||[]).filter(e=>(kind==='all'||e.kind===kind)&&Date.parse(e.endsAt)>=now&&(filter==='all'||filter==='today'&&e.startsAt.slice(0,10)<=today&&e.endsAt.slice(0,10)>=today||filter==='week'&&Date.parse(e.startsAt)<=now+7*86400000));
 return <section className="pilot-panel"><div className="pilot-title"><h2>Etkinlik</h2><button aria-label="Etkinlikleri yenile" onClick={()=>void events.refetch()} disabled={events.isFetching}><RefreshCw size={18}/></button></div><small>Antalya · Konser, tiyatro, festival ve diğer etkinlikler</small><div className="pharmacy-filter">{[['today','Bugün'],['week','7 gün'],['all','Tümü']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="pharmacy-filter">{[['all','Tümü'],['concert','Konser'],['theatre','Tiyatro'],['standup','Stand-up'],['festival','Festival'],['fair','Fuar']].map(([id,label])=><button key={id} aria-pressed={kind===id} onClick={()=>setKind(id)}>{label}</button>)}</div>{events.isPending&&<p role="status">Etkinlikler yükleniyor…</p>}{events.isError&&<Retry onClick={()=>void events.refetch()}/>} {events.data?.partial&&<small>Bazı etkinlik kaynaklarına şu an ulaşılamıyor.</small>} {!events.isPending&&!events.isError&&!items.length&&<p>Bu seçimde güncel etkinlik bulunamadı.</p>}{items.map(e=><article className="event-card" key={e.id}>{e.imageUrl&&<img src={e.imageUrl} alt={e.title} loading="lazy" onError={ev=>{ev.currentTarget.hidden=true;}}/>}<h3>{e.title}</h3><p>{new Date(e.startsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})}{e.startsAt.slice(0,10)!==e.endsAt.slice(0,10)&&` – ${new Date(e.endsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})}`}{e.hours&&` · ${e.hours}`}</p>{e.venue&&<p>{e.venue}</p>}{e.description&&<details><summary>Program bilgisi</summary><p>{e.description}</p></details>}<small>{e.source} · Ücret bilgisi doğrulanmadı</small><div className="event-links"><a className="solid-button" href={e.url} target="_blank" rel="noreferrer">Kaynak / bilet <ArrowUpRight size={16}/></a>{e.directionsUrl&&<a className="outline-button" href={e.directionsUrl} target="_blank" rel="noreferrer">Yol tarifi</a>}</div></article>)}<a className="pilot-source-link" href="https://www.antalya.bel.tr/tr/etkinlikler" target="_blank" rel="noreferrer">Belediyenin diğer etkinlikleri <ArrowUpRight size={16}/></a></section>;
}

export function PilotView({mode,location}:{mode:"transit"|"events"|"prices";location:Coordinates|null}) {return mode==="transit"?<TransitView location={location}/>:mode==="events"?<EventsView/>:<ProductPrices location={location}/>;}
