import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,ArrowUpRight,MapPin,Navigation,RefreshCw} from 'lucide-react';
import type {Coordinates,Place} from '../types';
import {useBackLayer} from '../hooks/useBackLayer';
const ProductPrices=lazy(()=>import('./ProductPrices').then(m=>({default:m.ProductPrices})));
const FishingView=lazy(()=>import('./FishingView'));
const CityServices=lazy(()=>import('./CityServices').then(m=>({default:m.OutagesView})));
const TrafficView=lazy(()=>import('./CityServices').then(m=>({default:m.TrafficView})));
const MapView=lazy(()=>import('./MapView').then(m=>({default:m.MapView})));

type Stop={id:string;name:string;lat:number;lng:number;routes:string[];distanceM:number};
type Bus={id:string;code:string;name:string;direction:number;minutes:number;stops:number|null};
type Event={id:string;title:string;startsAt:string;endsAt:string;hours:string|null;venue:string|null;imageUrl?:string;directionsUrl?:string;url:string;source:string;price:null;kind?:string;description?:string;priceLabel?:string|null};
async function get<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal});if(!r.ok)throw new Error('Kaynak alınamadı');return r.json();}
const routeLink=(p:Coordinates)=>`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;
function TransitStopsView({location,search}:{location:Coordinates|null;search:string}){
 const [selected,setSelected]=useState<Stop|null>(null),[map,setMap]=useState(false),[route,setRoute]=useState<{code:string;direction:number}|null>(null);
 useEffect(()=>{if(!selected)return;const y=window.scrollY;window.scrollTo(0,0);return ()=>window.scrollTo(0,y);},[!!selected]);
 useEffect(()=>{if(!route)return;const y=window.scrollY;window.scrollTo(0,0);return ()=>window.scrollTo(0,y);},[!!route]);
 useBackLayer(!!selected,()=>setSelected(null));
 useBackLayer(!!route,()=>setRoute(null));
 useEffect(()=>{document.documentElement.classList.toggle('transit-map-open',map&&!selected&&!route);return ()=>document.documentElement.classList.remove('transit-map-open');},[map,selected,route]);
 useEffect(()=>{setSelected(null);setRoute(null);},[location?.lat,location?.lng]);
 const inPilotArea=!!location&&location.lat>=36.7&&location.lat<=37.2&&location.lng>=30.3&&location.lng<=31.1;
 const coords=location?new URLSearchParams({lat:String(location.lat),lng:String(location.lng)}).toString():'';
 const stops=useQuery({queryKey:['transit-stops',location?.lat,location?.lng],queryFn:({signal})=>get<{stops:Stop[];coverage:string[];partial:boolean;catalogAt:string;catalogSize:number;stale:boolean}>(`/api/transit?${coords}`,signal),enabled:inPilotArea,staleTime:300000,retry:1});
 const buses=useQuery({queryKey:['transit-arrivals',selected?.id,location?.lat,location?.lng],queryFn:({signal})=>get<{buses:Bus[];fresh:boolean;sourceAt:string|null}>(`/api/transit?action=arrivals&stop=${selected!.id}&${coords}`,signal),enabled:!!selected&&!!location,refetchInterval:20000,retry:0});
 const path=useQuery({queryKey:['transit-route',route?.code,route?.direction],queryFn:({signal})=>get<{name:string;stops:Stop[]}>(`/api/transit?action=route&code=${encodeURIComponent(route!.code)}&direction=${route!.direction}&${coords}`,signal),enabled:!!route&&!!location,staleTime:3600000,retry:0});
 const filtered=(stops.data?.stops||[]).filter(s=>`${s.name} ${s.id} ${s.routes.join(' ')}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const places=useMemo(()=>filtered.map(s=>({id:`transit:${s.id}`,name:s.name,category:'transit',lat:s.lat,lng:s.lng,address:`Durak ${s.id} · ${s.routes.join(', ')}`,distanceM:s.distanceM,source:'Antalyakart / Kentkart'} satisfies Place)),[stops.data,search]);
 if(!location)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Yakın duraklar için üstteki Konum düğmesini kullan.</p><small>Antalya merkez pilotu</small></section>;
 if(!inPilotArea)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Bu pilot Antalya merkezde kullanılabilir.</p></section>;
 if(route)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setRoute(null)}><ArrowLeft size={18}/>Durağa dön</button><h2>{route.code}</h2><p>{path.data?.name||'Güzergâh'}</p><div className="pharmacy-filter">{[0,1].map(direction=><button key={direction} aria-pressed={route.direction===direction} onClick={()=>setRoute({...route,direction})}>{direction===0?'Gidiş':'Dönüş'}</button>)}</div>{path.isPending&&<p role="status">Duraklar yükleniyor…</p>}{path.isError&&<Retry onClick={()=>void path.refetch()}/>}<ol className="route-stops">{path.data?.stops.map(s=><li key={s.id}>{s.name}<small>{s.id}</small></li>)}</ol></section>;
 if(selected)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setSelected(null)}><ArrowLeft size={18}/>Duraklar</button><div className="pilot-title"><h2>{selected.name}</h2></div><small>Durak {selected.id} · Antalyakart / Kentkart</small><a className="outline-button pilot-directions" href={routeLink(selected)} target="_blank" rel="noreferrer"><Navigation size={16}/>Durağa yol tarifi</a><div className="arrivals-toolbar"><div><strong>Yaklaşan otobüsler</strong><small>20 saniyede bir güncellenir</small></div><button aria-label="Otobüsleri yenile" onClick={()=>void buses.refetch()} disabled={buses.isFetching}><RefreshCw size={18}/></button></div>{buses.isPending&&<p role="status">Yaklaşan araçlar yükleniyor…</p>}{buses.isError&&<Retry onClick={()=>void buses.refetch()}/>}<small className="pilot-updated">{buses.data?.sourceAt&&`Kaynak: ${new Date(buses.data.sourceAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}`}</small>{buses.data&&!buses.data.fresh&&<p role="alert">Kaynak güncel değil. Geliş tahminleri gösterilmiyor.</p>}{buses.data?.fresh&&buses.data.buses.length===0&&<p>Kaynak şu an yaklaşan araç bildirmiyor.</p>}{buses.data?.fresh&&!buses.isError&&buses.data.buses.map(b=><button className="bus-row" key={b.id} onClick={()=>setRoute({code:b.code,direction:b.direction})}><strong>{b.code}</strong><span>{b.name}<small>{b.stops===null?'':`${b.stops} durak uzakta`}</small></span><span className="bus-time">{b.minutes===0?'Yaklaşıyor':`${b.minutes} dk`}<small>Tahmini</small></span></button>)}<details className="stop-route-list"><summary>Bu duraktan geçen {selected.routes.length} hat</summary><div className="pharmacy-filter">{selected.routes.map(code=><button key={code} onClick={()=>setRoute({code,direction:0})}>{code}</button>)}</div></details></section>;
 return <section className={`pilot-panel ${map?'transit-map-panel':''}`}><div className="pilot-title"><h2>Yakın duraklar</h2><button onClick={()=>setMap(!map)}><MapPin size={17}/>{map?'Liste':'Harita'}</button></div>{stops.isPending&&<p role="status">Duraklar yükleniyor…</p>}{stops.isError&&<Retry onClick={()=>void stops.refetch()}/>} {stops.data?.stale&&<small>Durak kataloğunun güncellenmesi gerekiyor.</small>}{stops.data?.partial&&<small>Durak kaynağında bazı güzergâhlar eksik.</small>}{map&&<div className="pilot-map"><Suspense fallback={<p>Harita hazırlanıyor…</p>}><MapView memoryKey={`transit:${location.lat}:${location.lng}`} location={location} places={places} picking={false} onPick={()=>{}} onViewportChange={()=>{}} loading={stops.isFetching} onPlaceOpen={p=>{const stop=stops.data?.stops.find(s=>`transit:${s.id}`===p.id);if(stop)setSelected(stop);}}/></Suspense></div>}{!stops.isPending&&stops.data&&!filtered.length&&<p>2 km içinde eşleşen durak bulunamadı.</p>}{!map&&filtered.map(s=><button className="stop-row" key={s.id} onClick={()=>setSelected(s)}><MapPin size={20}/><span><strong>{s.name}</strong><small>{s.id} · Yaklaşık {s.distanceM} m</small><small>{s.routes.join(' · ')}</small></span></button>)}</section>;
}
export function TransitView({location,search,mode,setMode}:{location:Coordinates|null;search:string;mode:'stops'|'traffic';setMode:(mode:'stops'|'traffic')=>void}){
 return <><div className="pharmacy-filter transit-modes" aria-label="Ulaşım görünümü"><button aria-pressed={mode==='stops'} onClick={()=>setMode('stops')}>Duraklar</button><button aria-pressed={mode==='traffic'} onClick={()=>setMode('traffic')}>Trafik</button></div>{mode==='traffic'?<Suspense fallback={<p>Harita hazırlanıyor…</p>}><TrafficView location={location} search={search}/></Suspense>:<TransitStopsView location={location} search={search}/>}</>;
}
function Retry({onClick}:{onClick:()=>void}){return <div className="pilot-error" role="alert"><p>Kaynak şu an alınamıyor.</p><button className="plain-button" onClick={onClick}>Tekrar dene</button></div>;}
export function EventsView({search}:{search:string}){
 const events=useQuery({queryKey:['antalya-events'],queryFn:({signal})=>get<{items:Event[];coverage:string;fetchedAt:string;partial:boolean}>('/api/events',signal),staleTime:300000,refetchInterval:300000,retry:1});
 const now=Date.now();
 const items=(events.data?.items||[]).filter(e=>`${e.title} ${e.venue||''} ${({concert:'Konser',theatre:'Tiyatro',exhibition:'Sergi',children:'Çocuk',festival:'Festival',fair:'Fuar',standup:'Stand-up',other:'Diğer'} as Record<string,string>)[e.kind||'']||''}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))&&Date.parse(e.endsAt)>=now);
 return <section className="pilot-panel"><div className="pilot-title"><h2>Etkinlik</h2><button aria-label="Etkinlikleri yenile" onClick={()=>void events.refetch()} disabled={events.isFetching}><RefreshCw size={18}/></button></div><div className="pharmacy-filter"><button aria-pressed="true">Tümü</button></div>{events.isPending&&<p role="status">Etkinlikler yükleniyor…</p>}{events.isError&&<Retry onClick={()=>void events.refetch()}/>} {events.data?.partial&&<small>Bazı etkinlik kaynaklarına şu an ulaşılamıyor.</small>} {!events.isPending&&!events.isError&&!items.length&&<p>Bu seçimde güncel etkinlik bulunamadı.</p>}{items.map(e=><article className="event-card" key={e.id}>{e.imageUrl&&<img src={e.imageUrl} alt={e.title} loading="lazy" onError={ev=>{ev.currentTarget.hidden=true;}}/>}<h3>{e.title}</h3><p>{new Date(e.startsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})}{e.startsAt.slice(0,10)!==e.endsAt.slice(0,10)&&` – ${new Date(e.endsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})}`}{e.hours&&` · ${e.hours}`}</p>{e.venue&&<p>{e.venue}</p>}{e.description&&<details><summary>Program bilgisi</summary><p>{e.description}</p></details>}<small>{e.source} · {e.priceLabel||'Ücret bilgisi doğrulanmadı'}</small><div className="event-links"><a className="solid-button" href={e.url} target="_blank" rel="noreferrer">Kaynak / bilet <ArrowUpRight size={16}/></a>{!e.directionsUrl&&<small>Kesin konum doğrulanmadı.</small>}{e.directionsUrl&&<a className="outline-button" href={e.directionsUrl} target="_blank" rel="noreferrer">Yol tarifi</a>}</div></article>)}<a className="pilot-source-link" href="https://www.antalya.bel.tr/tr/etkinlikler" target="_blank" rel="noreferrer">Belediyenin diğer etkinlikleri <ArrowUpRight size={16}/></a></section>;
}

export function PilotView({mode,location,search,transitMode,onTransitModeChange,onChooseCoast,pickedCoast}:{onChooseCoast?:()=>void;pickedCoast?:Coordinates|null;transitMode:"stops"|"traffic";onTransitModeChange:(mode:"stops"|"traffic")=>void;mode:"fishing"|"transit"|"events"|"prices"|"outages";location:Coordinates|null;search:string}) {return mode==="fishing"?<FishingView location={location} onChooseCoast={onChooseCoast} pickedCoast={pickedCoast}/>:mode==="outages"?<CityServices location={location} search={search}/>:mode==="transit"?<TransitView location={location} search={search} mode={transitMode} setMode={onTransitModeChange}/>:mode==="events"?<EventsView search={search}/>:<ProductPrices location={location} input={search}/>;}
