import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {keepPreviousData,useQuery} from '@tanstack/react-query';
import {ArrowLeft,ArrowUpRight,MapPin,Navigation,RefreshCw} from 'lucide-react';
import type {Coordinates,Place} from '../types';
const MapView=lazy(()=>import('./MapView').then(m=>({default:m.MapView})));

type Stop={id:string;name:string;lat:number;lng:number;routes:string[];distanceM:number};
type Bus={id:string;code:string;name:string;direction:number;minutes:number;stops:number|null};
type Event={id:string;title:string;startsAt:string;endsAt:string;hours:string|null;venue:string|null;imageUrl?:string;directionsUrl?:string;url:string;source:string;price:null};
async function get<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal});if(!r.ok)throw new Error('Kaynak alınamadı');return r.json();}
const routeLink=(p:Coordinates)=>`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;
export function ProductPrices(){return <section className="pilot-panel price-source"><h2>Ürün fiyatları</h2><p>Yakın şubelerdeki ürünleri ve fiyatlarını resmi kaynakta karşılaştır.</p><a className="solid-button" href="https://marketfiyati.org.tr/" target="_blank" rel="noreferrer">Market Fiyatı’nda ara <ArrowUpRight size={17}/></a><small>Şube seçimi resmi sitede yapılır. Yakınım henüz fiyat verisini içeri aktarmıyor.</small></section>;}
export function TransitView({location}:{location:Coordinates|null}){
 const [selected,setSelected]=useState<Stop|null>(null),[map,setMap]=useState(false),[route,setRoute]=useState<{code:string;direction:number}|null>(null),[search,setSearch]=useState('');
 useEffect(()=>{setSelected(null);setRoute(null);},[location?.lat,location?.lng]);
 const inPilotArea=!!location&&location.lat>=36.7&&location.lat<=37.2&&location.lng>=30.3&&location.lng<=31.1;
 const coords=location?new URLSearchParams({lat:String(location.lat),lng:String(location.lng)}).toString():'';
 const stops=useQuery({queryKey:['transit-stops',location?.lat,location?.lng],queryFn:({signal})=>get<{stops:Stop[];coverage:string[];partial:boolean}>(`/api/transit?${coords}`,signal),enabled:inPilotArea,staleTime:300000,retry:1,placeholderData:keepPreviousData});
 const buses=useQuery({queryKey:['transit-arrivals',selected?.id,location?.lat,location?.lng],queryFn:({signal})=>get<{buses:Bus[];fresh:boolean;sourceAt:string|null}>(`/api/transit?action=arrivals&stop=${selected!.id}&${coords}`,signal),enabled:!!selected&&!!location,refetchInterval:20000,retry:0});
 const path=useQuery({queryKey:['transit-route',route?.code,route?.direction],queryFn:({signal})=>get<{name:string;stops:Stop[]}>(`/api/transit?action=route&code=${encodeURIComponent(route!.code)}&direction=${route!.direction}&${coords}`,signal),enabled:!!route&&!!location,staleTime:3600000,retry:0});
 const filtered=(stops.data?.stops||[]).filter(s=>`${s.name} ${s.id} ${s.routes.join(' ')}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const places=useMemo(()=>filtered.map(s=>({id:`transit:${s.id}`,name:s.name,category:'transit',lat:s.lat,lng:s.lng,address:`Durak ${s.id} · ${s.routes.join(', ')}`,distanceM:s.distanceM,source:'Antalyakart / Kentkart'} satisfies Place)),[stops.data,search]);
 if(!location)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Yakın duraklar için üstteki Konum düğmesini kullan.</p><small>Antalya merkez pilotu</small></section>;
 if(!inPilotArea)return <section className="pilot-panel"><h2>Ulaşım</h2><p>Bu pilot Antalya merkezde kullanılabilir.</p></section>;
 if(route)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setRoute(null)}><ArrowLeft size={18}/>Durağa dön</button><h2>{route.code}</h2><p>{path.data?.name||'Güzergâh'}</p>{path.isPending&&<p role="status">Duraklar yükleniyor…</p>}{path.isError&&<Retry onClick={()=>void path.refetch()}/>}<ol className="route-stops">{path.data?.stops.map(s=><li key={s.id}>{s.name}<small>{s.id}</small></li>)}</ol></section>;
 if(selected)return <section className="pilot-panel"><button className="pilot-back" onClick={()=>setSelected(null)}><ArrowLeft size={18}/>Duraklar</button><div className="pilot-title"><h2>{selected.name}</h2><button aria-label="Otobüsleri yenile" onClick={()=>void buses.refetch()} disabled={buses.isFetching}><RefreshCw size={18}/></button></div><small>Durak {selected.id} · Antalyakart / Kentkart</small><a className="outline-button pilot-directions" href={routeLink(selected)} target="_blank" rel="noreferrer"><Navigation size={16}/>Durağa yol tarifi</a>{buses.isPending&&<p role="status">Yaklaşan araçlar yükleniyor…</p>}{buses.isError&&<Retry onClick={()=>void buses.refetch()}/>}<small className="pilot-updated">{buses.data?.sourceAt&&`Kaynak: ${new Date(buses.data.sourceAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}`}</small>{buses.data&&!buses.data.fresh&&<p role="alert">Kaynak güncel değil. Geliş tahminleri gösterilmiyor.</p>}{buses.data?.fresh&&buses.data.buses.length===0&&<p>Kaynak şu an yaklaşan araç bildirmiyor.</p>}{buses.data?.fresh&&!buses.isError&&buses.data.buses.map(b=><button className="bus-row" key={b.id} onClick={()=>setRoute({code:b.code,direction:b.direction})}><strong>{b.code}</strong><span>{b.name}<small>{b.stops===null?'':`${b.stops} durak uzakta`}</small></span><span className="bus-time">{b.minutes===0?'Yaklaşıyor':`${b.minutes} dk`}<small>Tahmini</small></span></button>)}</section>;
 return <section className="pilot-panel"><div className="pilot-title"><h2>Yakın duraklar</h2><button onClick={()=>setMap(!map)}><MapPin size={17}/>{map?'Liste':'Harita'}</button></div><small>Antalya pilotu · KL08, LF09, LF10, AC03, DC15, VS18 güzergâhları</small><label className="search-box pilot-search"><input aria-label="Durak veya hat ara" placeholder="Durak veya hat ara" value={search} onChange={e=>setSearch(e.target.value)}/></label>{stops.isPending&&<p role="status">Duraklar yükleniyor…</p>}{stops.isError&&<Retry onClick={()=>void stops.refetch()}/>} {stops.data?.partial&&<small>Bazı güzergâhlar alınamadı.</small>}{map&&<div className="pilot-map"><Suspense fallback={<p>Harita hazırlanıyor…</p>}><MapView location={location} places={places} picking={false} onPick={()=>{}} onViewportChange={()=>{}} loading={stops.isFetching}/></Suspense></div>}{!stops.isPending&&stops.data&&!filtered.length&&<p>2 km içinde bu pilot güzergâhlara ait eşleşen durak bulunamadı.</p>}{filtered.map(s=><button className="stop-row" key={s.id} onClick={()=>setSelected(s)}><MapPin size={20}/><span><strong>{s.name}</strong><small>{s.id} · {s.distanceM} m kuş uçuşu</small><small>{s.routes.join(' · ')}</small></span></button>)}</section>;
}
function Retry({onClick}:{onClick:()=>void}){return <div className="pilot-error" role="alert"><p>Kaynak şu an alınamıyor.</p><button className="plain-button" onClick={onClick}>Tekrar dene</button></div>;}
export function EventsView(){
 const [filter,setFilter]=useState('all');const events=useQuery({queryKey:['antalya-events'],queryFn:({signal})=>get<{items:Event[];coverage:string;fetchedAt:string}>('/api/events',signal),staleTime:300000,refetchInterval:300000,retry:1});
 const now=Date.now();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const items=(events.data?.items||[]).filter(e=>Date.parse(e.endsAt)>=now&&(filter==='all'||filter==='today'&&e.startsAt.slice(0,10)<=today&&e.endsAt.slice(0,10)>=today||filter==='week'&&Date.parse(e.startsAt)<=now+7*86400000));
 return <section className="pilot-panel"><div className="pilot-title"><h2>Etkinlik</h2><button aria-label="Etkinlikleri yenile" onClick={()=>void events.refetch()} disabled={events.isFetching}><RefreshCw size={18}/></button></div><small>Antalya pilotu · Kitap Fuarı resmi programı</small><div className="pharmacy-filter">{[['today','Bugün'],['week','7 gün'],['all','Tümü']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{events.isPending&&<p role="status">Etkinlikler yükleniyor…</p>}{events.isError&&<Retry onClick={()=>void events.refetch()}/>} {!events.isPending&&!events.isError&&!items.length&&<p>Bu pilot kaynakta eşleşen güncel etkinlik yok.</p>}{items.map(e=><article className="event-card" key={e.id}>{e.imageUrl&&<img src={e.imageUrl} alt={e.title} loading="lazy" onError={ev=>{ev.currentTarget.hidden=true;}}/>}<h3>{e.title}</h3><p>{new Date(e.startsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})} – {new Date(e.endsAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'Europe/Istanbul'})}{e.hours&&` · ${e.hours}`}</p>{e.venue&&<p>{e.venue}</p>}<small>{e.source} · Ücret bilgisi doğrulanmadı</small><div className="event-links"><a className="solid-button" href={e.url} target="_blank" rel="noreferrer">Resmi program <ArrowUpRight size={16}/></a>{e.directionsUrl&&<a className="outline-button" href={e.directionsUrl} target="_blank" rel="noreferrer">Yol tarifi</a>}</div></article>)}<a className="pilot-source-link" href="https://www.antalya.bel.tr/tr/etkinlikler" target="_blank" rel="noreferrer">Belediyenin diğer etkinlikleri <ArrowUpRight size={16}/></a></section>;
}

export function PilotView({mode,location}:{mode:"transit"|"events"|"prices";location:Coordinates|null}) {return mode==="transit"?<TransitView location={location}/>:mode==="events"?<EventsView/>:<ProductPrices/>;}
