import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {RefreshCw} from 'lucide-react';
import type {Coordinates} from '../types';
import categories from '../../lib/price-categories.json';
async function get<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal});if(!r.ok)throw new Error('source');return r.json();}
const routeLink=(p:Coordinates)=>`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;
function Retry({onClick}:{onClick:()=>void}){return <div role="alert"><p>Kaynak şu an alınamıyor.</p><button onClick={onClick}>Tekrar dene</button></div>;}
type PriceOffer={id:string;name:string;market:string;lat:number;lng:number;distanceM:number;price:number;unitPrice:string;updatedAt:string;promotion:string|null};
type PriceProduct={id:string;title:string;quantity:string;imageUrl?:string;offers:PriceOffer[]};
const marketNames:Record<string,string>={a101:'A101',bim:'BİM',sok:'ŞOK',migros:'Migros',carrefour:'CarrefourSA',hakmar:'Hakmar',tarimkredi:'Tarım Kredi',tarim_kredi:'Tarım Kredi'};
const money=(value:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value);
function PriceCard({product}:{product:PriceProduct}){
 const [expanded,setExpanded]=useState(false);const chainPrices=[...new Set(product.offers.map(o=>o.market))].map(m=>Math.min(...product.offers.filter(o=>o.market===m).map(o=>o.price)));const low=Math.min(...chainPrices),high=Math.max(...chainPrices);const offers=expanded?product.offers:product.offers.slice(0,3);
 return <article className="product-price-card"><div className="product-price-heading">{product.imageUrl&&<img src={product.imageUrl} alt="" loading="lazy" onError={e=>{e.currentTarget.hidden=true;}}/>}<div><h3>{product.title}</h3><small>{product.quantity}</small></div></div>{chainPrices.length>1&&<p className="price-difference">Marketler arası fark: {money(high-low)} · %{(low>0?(high-low)/low*100:0).toLocaleString('tr-TR',{maximumFractionDigits:1})}</p>}{offers.map((offer,i)=><div className="product-offer" key={offer.id}><div><strong>{marketNames[offer.market]||offer.market}</strong><span>{offer.name}</span><small>Yaklaşık {offer.distanceM} m · {i===0&&chainPrices.length>1?'En düşük fiyat':''}</small><small>Kaynak güncellemesi: {new Date(offer.updatedAt).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}</small>{offer.promotion&&<small>{offer.promotion}</small>}<a href={routeLink(offer)} target="_blank" rel="noreferrer">Şubeye yol tarifi</a></div><div className="offer-price"><strong>{money(offer.price)}</strong><small>{offer.unitPrice}</small></div></div>)}{product.offers.length>3&&<button className="plain-button" onClick={()=>setExpanded(!expanded)}>{expanded?'Daha az göster':`${product.offers.length} fiyat kaydının tamamı`}</button>}</article>;
}
export function ProductPrices({location,input}:{location:Coordinates|null;input:string}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(0),[category,setCategory]=useState('all');
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(input.trim());setPage(0);},450);return ()=>clearTimeout(timer);},[input]);
 useEffect(()=>setPage(0),[location?.lat,location?.lng]);
 const inArea=!!location&&Number.isFinite(location.lat)&&Number.isFinite(location.lng)&&Math.abs(location.lat)<=90&&Math.abs(location.lng)<=180;
 const prices=useQuery({queryKey:['prices',location?.lat,location?.lng,search,page,category],queryFn:({signal})=>get<{products:PriceProduct[];alternatives?:PriceProduct[];partial?:boolean;depotCount:number;total:number;hasMore:boolean;radius:number}>(`/api/prices?${new URLSearchParams({lat:String(location!.lat),lng:String(location!.lng),q:search,page:String(page),category})}`,signal),enabled:inArea&&(search.length===0||search.length>=2),staleTime:300000,retry:1});
 const shared=(prices.data?.products||[]).filter(p=>new Set(p.offers.map(o=>o.market)).size>=2);const alternatives=[...(prices.data?.products||[]).filter(p=>new Set(p.offers.map(o=>o.market)).size<2),...(prices.data?.alternatives||[])].filter((p,i,a)=>a.findIndex(v=>v.id===p.id)===i);
 return <section className="pilot-panel"><div className="pilot-title"><h2>Ürün fiyatları</h2>{inArea&&<button aria-label="Fiyatları yenile" onClick={()=>void prices.refetch()} disabled={prices.isFetching}><RefreshCw size={18}/></button>}</div><div className="pharmacy-filter feature-categories" aria-label="Ürün kategorileri">{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setPage(0);}}>{c.label}</button>)}</div>{!location?<p>Yakındaki şube fiyatları için üstteki Konum düğmesini kullan.</p>:!inArea?<p>Geçerli bir konum seçerek yakındaki şube fiyatlarını görebilirsin.</p>:<>{search.length===1?<p>Aramak için en az iki harf yaz.</p>:<>{prices.isPending&&<p role="status">Yakındaki şubelerin fiyatları yükleniyor…</p>}{prices.isError&&<Retry onClick={()=>void prices.refetch()}/>} {prices.data&&!prices.isError&&<>{shared.length===0&&alternatives.length===0&&<p>{prices.data.depotCount?search?'Bu aramada güncel fiyat bulunamadı. Başka ürün veya marka deneyebilirsin.':'Bu çevrede birden fazla markette ortak fiyatı bulunan ürün bulunamadı. Ürün veya marka arayabilirsin.':'Bu konum çevresinde kaynakta kayıtlı şube bulunamadı.'}</p>}<p className="feature-note">Yakındaki 3 km içindeki şubeler · Son 48 saatte güncellenen kayıtlar. Aynı ürün ve paket karşılaştırılır; farklı marka veya paketler ayrı listelenir. Kaynak kapsamı tüm ürünleri içermez.</p>{prices.data.partial&&<p>Bazı kategori aramaları alınamadı; sonuçlar eksik olabilir.</p>}{shared.length>0&&<><h3>Aynı ürün, farklı marketler</h3>{shared.map(product=><PriceCard key={product.id} product={product}/>)}</>}{alternatives.length>0&&<><h3>Alternatif ürünler</h3><p>Bu ürünler için tek market zincirinde fiyat var; birbirleriyle aynı ürün olarak karşılaştırılmaz.</p>{alternatives.map(product=><PriceCard key={product.id} product={product}/>)}</>}<a href="https://www.marketfiyati.org.tr/" target="_blank" rel="noreferrer">Kaynak: Market Fiyatı</a>{(page>0||prices.data.hasMore)&&<div className="price-pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}>Önceki</button><span>{page+1}</span><button disabled={!prices.data.hasMore} onClick={()=>setPage(page+1)}>Sonraki</button></div>}</>}</>}</>}</section>;
}
