const TITCK='https://www.turkiye.gov.tr/saglik-titck-nobetci-eczane-sorgulama';
const LEGACY='https://eczaneadresi.com/api/public/v1/nearest-pharmacies';
const NOMINATIM='https://nominatim.openstreetmap.org/reverse';
const CACHE_TTL=5*60*1000,CACHE_LIMIT=120,cache=new Map();
const PROVINCES=['','Adana','Adıyaman','Afyonkarahisar','Ağrı','Amasya','Ankara','Antalya','Artvin','Aydın','Balıkesir','Bilecik','Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum','Denizli','Diyarbakır','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir','Gaziantep','Giresun','Gümüşhane','Hakkari','Hatay','Isparta','Mersin','İstanbul','İzmir','Kars','Kastamonu','Kayseri','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa','Kahramanmaraş','Mardin','Muğla','Muş','Nevşehir','Niğde','Ordu','Rize','Sakarya','Samsun','Siirt','Sinop','Sivas','Tekirdağ','Tokat','Trabzon','Tunceli','Şanlıurfa','Uşak','Van','Yozgat','Zonguldak','Aksaray','Bayburt','Karaman','Kırıkkale','Batman','Şırnak','Bartın','Ardahan','Iğdır','Yalova','Karabük','Kilis','Osmaniye','Düzce'];

function norm(v=''){return String(v).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim()}
function decode(v=''){const e={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};return String(v).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&([a-z]+);/gi,(m,n)=>e[n.toLowerCase()]??m)}
function text(v=''){return decode(String(v).replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function attr(tag,name){return getMatch(String(tag),new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`,'i'),1)}
function getMatch(v,re,i=1){const m=v.match(re);return m?decode(m[i]||''):''}
function phone(v=''){
  const raw=String(v).trim();
  const m=raw.match(/(?:\+?90[\s.-]*)?0?[\s.-]*\(?(\d{3})\)?[\s.-]*(\d{3})[\s.-]*(\d{4})/);
  if(m)return `0${m[1]}${m[2]}${m[3]}`;
  const d=raw.replace(/\D/g,'');
  if(d.length===10)return `0${d}`;
  if(d.length===11&&d.startsWith('0'))return d;
  return '';
}
function trDate(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Istanbul',day:'2-digit',month:'2-digit',year:'numeric'}).formatToParts(new Date()),x=t=>p.find(a=>a.type===t)?.value||'';return `${x('day')}/${x('month')}/${x('year')}`}
function meters(a,b,c,d){const r=6371000,k=Math.PI/180,x=(c-a)*k,y=(d-b)*k,q=Math.sin(x/2)**2+Math.cos(a*k)*Math.cos(c*k)*Math.sin(y/2)**2;return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function key(lat,lng,radius,limit){return `${trDate()}:${lat.toFixed(3)}:${lng.toFixed(3)}:${Math.round(radius/500)*500}:${limit}`}
function readCache(k){const v=cache.get(k);if(!v)return null;if(Date.now()-v.at>CACHE_TTL){cache.delete(k);return null}return v.data}
function writeCache(k,data){if(cache.size>=CACHE_LIMIT)cache.delete(cache.keys().next().value);cache.set(k,{at:Date.now(),data})}

function cookieHeader(jar){return [...jar].map(([k,v])=>`${k}=${v}`).join('; ')}
function absorb(headers,jar){const values=typeof headers.getSetCookie==='function'?headers.getSetCookie():(headers.get('set-cookie')?[headers.get('set-cookie')]:[]);for(const raw of values)for(const c of String(raw).split(/,(?=\s*[^;,=]+=[^;,]+)/g)){const first=c.split(';',1)[0],i=first.indexOf('=');if(i>0)jar.set(first.slice(0,i).trim(),first.slice(i+1).trim())}}
async function request(url,{method='GET',body,jar=new Map(),timeout=6500,headers={}}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const h={'User-Agent':'Mozilla/5.0 (compatible; Yakinim/1.0; +https://yakinim.vercel.app/)','Accept-Language':'tr-TR,tr;q=0.9,en;q=0.7','Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Referer':TITCK,...headers};if(jar.size)h.Cookie=cookieHeader(jar);const response=await fetch(url,{method,body,headers:h,signal:controller.signal,redirect:'follow'});absorb(response.headers,jar);if(!response.ok)throw new Error(`upstream_${response.status}`);return await response.text()}finally{clearTimeout(timer)}}

function parsePageContext(html){const body=html.match(/<body\b[^>]*>/i)?.[0]||'',dates=[...html.matchAll(/<input\b[^>]*>/gi)].map(m=>m[0]).filter(t=>attr(t,'name')==='nobetTarihi'&&attr(t,'type').toLowerCase()==='radio').map(t=>attr(t,'value')).filter(Boolean);return{token:attr(body,'data-token'),dates}}
function parseRows(html){const table=html.match(/<table\b[^>]*id=["']searchTable["'][^>]*>([\s\S]*?)<\/table>/i)?.[1]||'',tbody=table.match(/<tbody\b[^>]*>([\s\S]*?)<\/tbody>/i)?.[1]||table,rows=[];let rowIndex=0;for(const m of tbody.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...m[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>text(x[1]));if(cells.length<4)continue;rows.push({rowIndex,district:cells[0],name:cells[1],address:cells[2],phone:phone(cells[3])});rowIndex++}return rows}
function parseCoordinates(html){const a=html.match(/var\s+latti\s*=\s*parseFloat\(([\d.]+)\)/i),b=html.match(/var\s+longi\s*=\s*parseFloat\(([\d.]+)\)/i);if(!a||!b)return null;const latitude=Number(a[1]),longitude=Number(b[1]);return Number.isFinite(latitude)&&Number.isFinite(longitude)?{latitude,longitude}:null}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let i=0;async function worker(){while(i<items.length){const n=i++;try{out[n]=await fn(items[n],n)}catch{out[n]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}

async function reverse(lat,lng){const url=new URL(NOMINATIM);url.searchParams.set('format','jsonv2');url.searchParams.set('lat',lat);url.searchParams.set('lon',lng);url.searchParams.set('zoom','10');url.searchParams.set('addressdetails','1');const c=new AbortController(),timer=setTimeout(()=>c.abort(),4500);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Yakinim/1.0 (https://yakinim.vercel.app/)','Accept-Language':'tr-TR,tr;q=0.9','Accept':'application/json'}});if(!r.ok)throw new Error(`reverse_${r.status}`);const p=await r.json(),a=p.address||{},iso=Object.entries(a).find(([k,v])=>/^ISO3166-2-lvl\d+$/i.test(k)&&/^TR-\d{2}$/i.test(String(v)))?.[1];let plate=iso?String(iso).slice(-2):'';const province=a.province||a.state||a.region||'';if(!plate){const n=PROVINCES.findIndex(x=>norm(x)===norm(province));if(n>0)plate=String(n).padStart(2,'0')}return{plate,province,district:a.town||a.county||a.city_district||a.municipality||''}}finally{clearTimeout(timer)}}

async function official({lat,lng,radius,limit}){const loc=await reverse(lat,lng);if(!/^\d{2}$/.test(loc.plate))throw new Error('province_unresolved');const jar=new Map(),page=await request(TITCK,{jar}),ctx=parsePageContext(page),date=trDate();if(!ctx.token||!ctx.dates.includes(date))throw new Error('official_context_unavailable');const form=new URLSearchParams({ilkod:loc.plate,'ilkod-address-il':loc.plate,'ilkod-address-ilce':'',nobetTarihi:date,token:ctx.token,btn:'Sorgula'});await request(`${TITCK}?submit`,{method:'POST',body:form.toString(),jar,headers:{'Content-Type':'application/x-www-form-urlencoded'}});const rows=parseRows(await request(`${TITCK}?nobetci=Eczaneler`,{jar}));if(!rows.length)throw new Error('official_empty_unverified');const d=norm(loc.district),same=d?rows.filter(x=>{const r=norm(x.district);return r===d||r.includes(d)||d.includes(r)}):[],candidates=same.length?same:rows;const located=await mapLimit(candidates,6,async row=>{const body=new URLSearchParams({harita:'Goster',index:String(row.rowIndex)}).toString(),html=await request(`${TITCK}?harita=Goster&index=${row.rowIndex}`,{method:'POST',body,jar,timeout:4200,headers:{'Content-Type':'application/x-www-form-urlencoded'}}),point=parseCoordinates(html);if(!point)return{id:`titck:${loc.plate}:${row.rowIndex}`,name:row.name,address:row.address,phone:row.phone,latitude:null,longitude:null,distance_m:null,district:row.district,source:'turkiye.gov.tr'};const distance_m=Math.round(meters(lat,lng,point.latitude,point.longitude));return{id:`titck:${loc.plate}:${norm(row.name).replace(/\s+/g,'-')}:${row.rowIndex}`,name:row.name,address:row.address,phone:row.phone,latitude:point.latitude,longitude:point.longitude,distance_m,district:row.district,source:'turkiye.gov.tr'}});return{pharmacies:located.filter(Boolean).filter(x=>x.latitude===null||x.distance_m<=radius).sort((a,b)=>a.distance_m-b.distance_m).slice(0,limit),source:'turkiye.gov.tr',queryDate:date,province:loc.province,district:loc.district}}

async function legacy({lat,lng,radius,limit}){const url=new URL(LEGACY);url.searchParams.set('lat',lat.toFixed(6));url.searchParams.set('lng',lng.toFixed(6));url.searchParams.set('radius',radius);url.searchParams.set('limit',limit);const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`legacy_${r.status}`);const p=await r.json(),rows=p.pharmacies||p.data||[];return{pharmacies:rows.map((x,i)=>({id:x.id??x.slug??`legacy:${i}`,name:x.name||x.pharmacy_name||'Nöbetçi Eczane',address:x.address||x.address_text||'Adres bilgisi yok',phone:phone(x.phone||x.phone_number||''),latitude:Number(x.latitude??x.lat??x.location?.lat),longitude:Number(x.longitude??x.lng??x.lon??x.location?.lng??x.location?.lon),distance_m:Number(x.distance_m)||Math.round((Number(x.distance_km??x.distanceKm??x.distance)||0)*1000),source:'legacy-fallback'})).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)),source:'legacy-fallback'}}finally{clearTimeout(timer)}}

module.exports=async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');res.setHeader('Cache-Control','no-store');return res.status(405).json({error:'method_not_allowed'})}const p=new URL(req.url,'https://yakinim.vercel.app').searchParams,lat=Number(p.get('lat')),lng=Number(p.get('lng')),radius=Math.min(25000,Math.max(500,Number(p.get('radius')||7000))),limit=Math.min(50,Math.max(1,Number(p.get('limit')||25)));if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180){res.setHeader('Cache-Control','no-store');return res.status(400).json({error:'invalid_location'})}const k=key(lat,lng,radius,limit),cached=readCache(k);if(cached){res.setHeader('X-Yakinim-Cache','HIT');res.setHeader('X-Yakinim-Duty-Source',cached.source||'unknown');res.setHeader('Cache-Control','no-store');return res.status(200).json(cached)}try{let data;try{data=await official({lat,lng,radius,limit})}catch(error){console.warn('Official duty source unavailable:',error.message);data=await legacy({lat,lng,radius,limit})}data.fetchedAt=new Date().toISOString();data.queryDate=data.queryDate||trDate();writeCache(k,data);res.setHeader('X-Yakinim-Cache','MISS');res.setHeader('X-Yakinim-Duty-Source',data.source||'unknown');res.setHeader('Cache-Control','no-store');return res.status(200).json(data)}catch(error){console.error('Duty providers unavailable:',error.message);res.setHeader('Cache-Control','no-store');return res.status(503).json({error:'duty_unavailable'})}};
module.exports._private={parsePageContext,parseRows,parseCoordinates,normalizeText:norm,distanceMeters:meters,normalizePhone:phone,reverseLocation:reverse,fetchOfficial:official,fetchLegacy:legacy};